# Training Dataset

This notebook is created to experiment and work on historical stock price data.

I start with converting the dataset (downloaded from Kaggle, author used yfinance) to parquet format. I am using this dataset for my personal and educational purposes.

In [10]:
# import data into pandas dataframe
import pandas as pd

def import_data(file_path: str) -> pd.DataFrame:
    try:
        data = pd.read_csv(file_path)
        return data
    except Exception as e:
        print(f"An error occurred while importing data: {e}")
        return pd.DataFrame()

In [ ]:
import yfinance as yf

def load_history(ticker: str, start_date: str, end_date: str) -> pd.DataFrame:
    try:
        stock = yf.Ticker(ticker)
        history = stock.history(
            start=start_date, 
            end=end_date, 
            interval="1d", 
            prepost=False, 
            auto_adjust = False) # auto_adjust added to get same data as in csv files
        return history
    except Exception as e:
        print(f"An error occurred while loading history: {e}")
        return pd.DataFrame()

The following code loops through the yfinance folder and convert them to the parquet format. The dataset from Kaggle contains data until April 2020, I downloaded last 5 years and 8 months of data for test dataset and saving them to parquet format as well. It skips the tickers that probably no longer exist.

The following code is disabled (condition) on purpose to avoid running again.

In [15]:
if False: # adding the condition to avoid running this code again. 
    from pathlib import Path
    import time
    Path("parquet_train_data").mkdir(parents=True, exist_ok=True)
    Path("parquet_test_data").mkdir(parents=True, exist_ok=True)

    files = Path("yfinance_stock_data").glob("*.csv")
    for stock in files:
        ticker = stock.stem
        try:
            df_test = load_history(ticker, "2020-04-02", "2026-02-01")
            if df_test.empty:
                print(f"No data found for {ticker}. Skipping...")
                continue 
            if hasattr(df_test.index, 'tz') and df_test.index.tz is not None:
                df_test.index = df_test.index.tz_localize(None)
            df_test = df_test[['Open', 'High', 'Low', 'Close', 'Adj Close','Volume']]
            df_test.to_parquet(f"parquet_test_data/{ticker}.parquet", engine='pyarrow', compression='snappy')
            df_train = import_data(stock) 
            df_train['Date'] = pd.to_datetime(df_train['Date'])
            df_train.set_index('Date', inplace=True)
            df_train.to_parquet(f"parquet_train_data/{ticker}.parquet", engine='pyarrow', compression='snappy')
            time.sleep(1)  # To avoid rate limit on yfinance API
        except Exception as e:
            print(f"An error occurred while processing {ticker}: {e}")

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANTE"}}}
$ANTE: possibly delisted; no timezone found

No data found for ANTE. Skipping...

$UNT: possibly delisted; no timezone found

No data found for UNT. Skipping...

$GPL: possibly delisted; no timezone found

No data found for GPL. Skipping...

$TEAF: possibly delisted; no timezone found

No data found for TEAF. Skipping...

$GFED: possibly delisted; no timezone found

No data found for GFED. Skipping...

$RHE: possibly delisted; no timezone found

No data found for RHE. Skipping...

$CARO: possibly delisted; no timezone found

No data found for CARO. Skipping...

$NBW: possibly delisted; no timezone found

No data found for NBW. Skipping...

$PIC: possibly delisted; no timezone found

No data found for PIC. Skipping...

$PRGX: possibly delisted; no timezone found
$ERF: possibly delisted; no timezone found

No data found for PRGX. Skipping...
No data found for ERF. Skipping...

$CHAP: possibly delisted; no timezone found

No data found for CHAP. Skipping...

$CHNGU: possibly delisted; no timezone found

No data found for CHNGU. Skipping...

$KSM: possibly delisted; no timezone found

No data found for KSM. Skipping...

$IMAB: possibly delisted; no timezone found

No data found for IMAB. Skipping...

$MNCLU: possibly delisted; no timezone found

No data found for MNCLU. Skipping...

$SVT: possibly delisted; no timezone found

No data found for SVT. Skipping...

$XLRN: possibly delisted; no timezone found

No data found for XLRN. Skipping...

$DTQ: possibly delisted; no timezone found

No data found for DTQ. Skipping...

$AIH: possibly delisted; no timezone found

No data found for AIH. Skipping...

$MN: possibly delisted; no timezone found

No data found for MN. Skipping...

$VIE: possibly delisted; no timezone found

No data found for VIE. Skipping...

$DPHC: possibly delisted; no timezone found

No data found for DPHC. Skipping...

$BFRA: possibly delisted; no timezone found

No data found for BFRA. Skipping...

$SAND: possibly delisted; no timezone found

No data found for SAND. Skipping...

$JNCE: possibly delisted; no timezone found

No data found for JNCE. Skipping...

$CEQP: possibly delisted; no timezone found

No data found for CEQP. Skipping...

$DRRX: possibly delisted; no timezone found
$NPAUU: possibly delisted; no timezone found

No data found for DRRX. Skipping...
No data found for NPAUU. Skipping...

$MNCL: possibly delisted; no timezone found

No data found for MNCL. Skipping...

$GLEO: possibly delisted; no timezone found

No data found for GLEO. Skipping...

$MRO: possibly delisted; no timezone found

No data found for MRO. Skipping...

$OCSI: possibly delisted; no timezone found

No data found for OCSI. Skipping...

$HMI: possibly delisted; no timezone found

No data found for HMI. Skipping...

$SSPK: possibly delisted; no timezone found

No data found for SSPK. Skipping...

$SNR: possibly delisted; no timezone found

No data found for SNR. Skipping...

$SHSP: possibly delisted; no timezone found

No data found for SHSP. Skipping...

$CHN: possibly delisted; no timezone found
$YGYIP: possibly delisted; no timezone found

No data found for CHN. Skipping...
No data found for YGYIP. Skipping...

$EVBN: possibly delisted; no timezone found

No data found for EVBN. Skipping...

$FSCT: possibly delisted; no timezone found
$NYMTP: possibly delisted; no timezone found

No data found for FSCT. Skipping...
No data found for NYMTP. Skipping...

$SNE: possibly delisted; no timezone found
$NLSN: possibly delisted; no timezone found

No data found for SNE. Skipping...
No data found for NLSN. Skipping...

$VRAY: possibly delisted; no timezone found

No data found for VRAY. Skipping...

$WSTG: possibly delisted; no timezone found

No data found for WSTG. Skipping...

$MIE: possibly delisted; no timezone found

No data found for MIE. Skipping...

$CEI: possibly delisted; no timezone found

No data found for CEI. Skipping...

$SCU: possibly delisted; no timezone found
$PFMT: possibly delisted; no timezone found

No data found for SCU. Skipping...
No data found for PFMT. Skipping...

$VRNA: possibly delisted; no timezone found
$CGA: possibly delisted; no timezone found

No data found for VRNA. Skipping...
No data found for CGA. Skipping...

$TVTY: possibly delisted; no timezone found

No data found for TVTY. Skipping...

$STMP: possibly delisted; no timezone found

No data found for STMP. Skipping...

$PFNX: possibly delisted; no timezone found

No data found for PFNX. Skipping...

$STON: possibly delisted; no timezone found

No data found for STON. Skipping...

$TDA: possibly delisted; no timezone found

No data found for TDA. Skipping...

$HARP: possibly delisted; no timezone found

No data found for HARP. Skipping...

$PHCF: possibly delisted; no timezone found

No data found for PHCF. Skipping...

$VRML: possibly delisted; no timezone found

No data found for VRML. Skipping...

$TZAC: possibly delisted; no timezone found

No data found for TZAC. Skipping...

$TIF: possibly delisted; no timezone found

No data found for TIF. Skipping...

$ARC: possibly delisted; no timezone found

No data found for ARC. Skipping...

$DLA: possibly delisted; no timezone found
$STAR: possibly delisted; no timezone found

No data found for DLA. Skipping...
No data found for STAR. Skipping...

$MDC: possibly delisted; no timezone found

No data found for MDC. Skipping...

$SJIJ: possibly delisted; no timezone found

No data found for SJIJ. Skipping...

$AMSWA: possibly delisted; no timezone found

No data found for AMSWA. Skipping...

$FTR: possibly delisted; no timezone found

No data found for FTR. Skipping...

$FUV: possibly delisted; no timezone found

No data found for FUV. Skipping...

$DNI: possibly delisted; no timezone found

No data found for DNI. Skipping...

$TSCAP: possibly delisted; no timezone found

No data found for TSCAP. Skipping...

$FTSI: possibly delisted; no timezone found

No data found for FTSI. Skipping...

$DESP: possibly delisted; no timezone found

No data found for DESP. Skipping...

$CS: possibly delisted; no timezone found

No data found for CS. Skipping...

$ATRS: possibly delisted; no timezone found

No data found for ATRS. Skipping...

$HBP: possibly delisted; no timezone found

No data found for HBP. Skipping...

$DUC: possibly delisted; no timezone found
$DTP: possibly delisted; no timezone found

No data found for DUC. Skipping...
No data found for DTP. Skipping...

$FLT: possibly delisted; no timezone found

No data found for FLT. Skipping...

$HMSY: possibly delisted; no timezone found

No data found for HMSY. Skipping...

$LK: possibly delisted; no timezone found

No data found for LK. Skipping...

$AVEO: possibly delisted; no timezone found

No data found for AVEO. Skipping...

$ICLK: possibly delisted; no timezone found
$IMAC: possibly delisted; no timezone found

No data found for ICLK. Skipping...
No data found for IMAC. Skipping...

$WBC: possibly delisted; no timezone found

No data found for WBC. Skipping...

$ALACR: possibly delisted; no timezone found
$ALYA: possibly delisted; no timezone found

No data found for ALACR. Skipping...
No data found for ALYA. Skipping...

$ZGNX: possibly delisted; no timezone found

No data found for ZGNX. Skipping...

$WBT: possibly delisted; no timezone found

No data found for WBT. Skipping...

$NMY: possibly delisted; no timezone found

No data found for NMY. Skipping...

$MFNC: possibly delisted; no timezone found

No data found for MFNC. Skipping...

$LEAF: possibly delisted; no timezone found

No data found for LEAF. Skipping...

$NCR: possibly delisted; no timezone found

No data found for NCR. Skipping...

$ITCI: possibly delisted; no timezone found

No data found for ITCI. Skipping...

$HWCC: possibly delisted; no timezone found

No data found for HWCC. Skipping...

$GIX: possibly delisted; no timezone found
$MHLD: possibly delisted; no timezone found

No data found for GIX. Skipping...
No data found for MHLD. Skipping...

$IEC: possibly delisted; no timezone found

No data found for IEC. Skipping...

$NOVA: possibly delisted; no timezone found

No data found for NOVA. Skipping...

$OIIM: possibly delisted; no timezone found

No data found for OIIM. Skipping...

$GLADL: possibly delisted; no timezone found

No data found for GLADL. Skipping...

$PBBI: possibly delisted; no timezone found

No data found for PBBI. Skipping...

$NXTD: possibly delisted; no timezone found

No data found for NXTD. Skipping...

$UBA: possibly delisted; no timezone found

No data found for UBA. Skipping...

$PACQU: possibly delisted; no timezone found

No data found for PACQU. Skipping...

$SLGG: possibly delisted; no timezone found

No data found for SLGG. Skipping...

$EGF: possibly delisted; no timezone found

No data found for EGF. Skipping...

$EYES: possibly delisted; no timezone found

No data found for EYES. Skipping...

$TRNE: possibly delisted; no timezone found

No data found for TRNE. Skipping...

$PBTS: possibly delisted; no timezone found

No data found for PBTS. Skipping...

$BBL: possibly delisted; no timezone found

No data found for BBL. Skipping...

$TROV: possibly delisted; no timezone found

No data found for TROV. Skipping...

$BPMX: possibly delisted; no timezone found

No data found for BPMX. Skipping...

$MTEM: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for MTEM. Skipping...

$CORV: possibly delisted; no timezone found

No data found for CORV. Skipping...

$TUES: possibly delisted; no timezone found

No data found for TUES. Skipping...

$PTVCA: possibly delisted; no timezone found

No data found for PTVCA. Skipping...

$GSV: possibly delisted; no timezone found

No data found for GSV. Skipping...

$GPM: possibly delisted; no timezone found

No data found for GPM. Skipping...

$DTEA: possibly delisted; no timezone found
$AEGN: possibly delisted; no timezone found

No data found for DTEA. Skipping...
No data found for AEGN. Skipping...

$SRAC: possibly delisted; no timezone found
$IVAC: possibly delisted; no timezone found

No data found for SRAC. Skipping...
No data found for IVAC. Skipping...

$LBC: possibly delisted; no timezone found

No data found for LBC. Skipping...

$IBKCO: possibly delisted; no timezone found

No data found for IBKCO. Skipping...

$WLTW: possibly delisted; no timezone found

No data found for WLTW. Skipping...

$GPX: possibly delisted; no timezone found

No data found for GPX. Skipping...

$MORF: possibly delisted; no timezone found

No data found for MORF. Skipping...

$EGOV: possibly delisted; no timezone found

No data found for EGOV. Skipping...

$LNDC: possibly delisted; no timezone found

No data found for LNDC. Skipping...

$CSLT: possibly delisted; no timezone found
$REV: possibly delisted; no timezone found

No data found for CSLT. Skipping...
No data found for REV. Skipping...

$PACQW: possibly delisted; no timezone found
$AGRX: possibly delisted; no timezone found

No data found for PACQW. Skipping...
No data found for AGRX. Skipping...

$NTN: possibly delisted; no timezone found

No data found for NTN. Skipping...

$BNSO: possibly delisted; no timezone found
$IMMU: possibly delisted; no timezone found

No data found for BNSO. Skipping...
No data found for IMMU. Skipping...

$IEA: possibly delisted; no timezone found

No data found for IEA. Skipping...

$GIM: possibly delisted; no timezone found

No data found for GIM. Skipping...

$EPZM: possibly delisted; no timezone found

No data found for EPZM. Skipping...

$PHD: possibly delisted; no timezone found

No data found for PHD. Skipping...

$SURF: possibly delisted; no timezone found
$BROG: possibly delisted; no timezone found

No data found for SURF. Skipping...
No data found for BROG. Skipping...

$CSTR: possibly delisted; no timezone found

No data found for CSTR. Skipping...

$CSWI: possibly delisted; no timezone found

No data found for CSWI. Skipping...

$RCII: possibly delisted; no timezone found

No data found for RCII. Skipping...

$XSPA: possibly delisted; no timezone found

No data found for XSPA. Skipping...

$CXDC: possibly delisted; no timezone found

No data found for CXDC. Skipping...

$WBA: possibly delisted; no timezone found

No data found for WBA. Skipping...

$CTRC: possibly delisted; no timezone found

No data found for CTRC. Skipping...

$MYOV: possibly delisted; no timezone found

No data found for MYOV. Skipping...

$ESGR: possibly delisted; no timezone found

No data found for ESGR. Skipping...

$SMTS: possibly delisted; no timezone found
$YTEN: possibly delisted; no timezone found

No data found for SMTS. Skipping...
No data found for YTEN. Skipping...

$AVGR: possibly delisted; no timezone found

No data found for AVGR. Skipping...

$SAMAU: possibly delisted; no timezone found

No data found for SAMAU. Skipping...

$ODT: possibly delisted; no timezone found

No data found for ODT. Skipping...

$SVBI: possibly delisted; no timezone found

No data found for SVBI. Skipping...

$AMRS: possibly delisted; no timezone found

No data found for AMRS. Skipping...

$AJXA: possibly delisted; no timezone found
$VER: possibly delisted; no timezone found

No data found for AJXA. Skipping...
No data found for VER. Skipping...

$BSIG: possibly delisted; no timezone found

No data found for BSIG. Skipping...

$TSRI: possibly delisted; no timezone found

No data found for TSRI. Skipping...

$AY: possibly delisted; no timezone found

No data found for AY. Skipping...

$CRSA: possibly delisted; no timezone found
$SYX: possibly delisted; no timezone found

No data found for CRSA. Skipping...
No data found for SYX. Skipping...

$SZC: possibly delisted; no timezone found

No data found for SZC. Skipping...

$DISH: possibly delisted; no timezone found

No data found for DISH. Skipping...

$DNK: possibly delisted; no timezone found

No data found for DNK. Skipping...

$ARA: possibly delisted; no timezone found

No data found for ARA. Skipping...

$GAINL: possibly delisted; no timezone found

No data found for GAINL. Skipping...

$ASRVP: possibly delisted; no timezone found

No data found for ASRVP. Skipping...

$SMMF: possibly delisted; no timezone found

No data found for SMMF. Skipping...

$SMAR: possibly delisted; no timezone found

No data found for SMAR. Skipping...

$SCA: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for SCA. Skipping...

$PCSB: possibly delisted; no timezone found

No data found for PCSB. Skipping...

$ACIA: possibly delisted; no timezone found

No data found for ACIA. Skipping...

$SBE: possibly delisted; no timezone found

No data found for SBE. Skipping...

$OFSSI: possibly delisted; no timezone found

No data found for OFSSI. Skipping...

$UEPS: possibly delisted; no timezone found

No data found for UEPS. Skipping...

$WTRU: possibly delisted; no timezone found

No data found for WTRU. Skipping...

$GNFT: possibly delisted; no timezone found

No data found for GNFT. Skipping...

$HTIA: possibly delisted; no timezone found

No data found for HTIA. Skipping...

$ESSA: possibly delisted; no timezone found

No data found for ESSA. Skipping...

$VRNT: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for VRNT. Skipping...

$EVOK: possibly delisted; no timezone found

No data found for EVOK. Skipping...

$RWLK: possibly delisted; no timezone found

No data found for RWLK. Skipping...

$CBLI: possibly delisted; no timezone found

No data found for CBLI. Skipping...

$CBAY: possibly delisted; no timezone found

No data found for CBAY. Skipping...

$MFH: possibly delisted; no timezone found

No data found for MFH. Skipping...

$HJLI: possibly delisted; no timezone found
$STCN: possibly delisted; no timezone found

No data found for HJLI. Skipping...
No data found for STCN. Skipping...

$DMF: possibly delisted; no timezone found

No data found for DMF. Skipping...

$VBFC: possibly delisted; no timezone found

No data found for VBFC. Skipping...

$GAINM: possibly delisted; no timezone found
$INBKL: possibly delisted; no timezone found

No data found for GAINM. Skipping...
No data found for INBKL. Skipping...

$CHL: possibly delisted; no timezone found

No data found for CHL. Skipping...

$SNP: possibly delisted; no timezone found

No data found for SNP. Skipping...

$STAF: possibly delisted; no timezone found
$LJPC: possibly delisted; no timezone found

No data found for STAF. Skipping...
No data found for LJPC. Skipping...

$NWGI: possibly delisted; no timezone found

No data found for NWGI. Skipping...

$CIH: possibly delisted; no timezone found

No data found for CIH. Skipping...

$CLNY: possibly delisted; no timezone found

No data found for CLNY. Skipping...

$HCFT: possibly delisted; no timezone found

No data found for HCFT. Skipping...

$BCOM: possibly delisted; no timezone found
$CLXT: possibly delisted; no timezone found

No data found for BCOM. Skipping...
No data found for CLXT. Skipping...

$CNAT: possibly delisted; no timezone found

No data found for CNAT. Skipping...

$CBTX: possibly delisted; no timezone found

No data found for CBTX. Skipping...

$HNP: possibly delisted; no timezone found

No data found for HNP. Skipping...

$SYN: possibly delisted; no timezone found

No data found for SYN. Skipping...

$NPTN: possibly delisted; no timezone found

No data found for NPTN. Skipping...

$EXTN: possibly delisted; no timezone found

No data found for EXTN. Skipping...

$BSGM: possibly delisted; no timezone found

No data found for BSGM. Skipping...

$SUM: possibly delisted; no timezone found

No data found for SUM. Skipping...

$TZACU: possibly delisted; no timezone found

No data found for TZACU. Skipping...

$BRPAR: possibly delisted; no timezone found

No data found for BRPAR. Skipping...

$ANCN: possibly delisted; no timezone found

No data found for ANCN. Skipping...

$MTSC: possibly delisted; no timezone found
$NNA: possibly delisted; no timezone found

No data found for MTSC. Skipping...
No data found for NNA. Skipping...

$SKYS: possibly delisted; no timezone found

No data found for SKYS. Skipping...

$TURN: possibly delisted; no timezone found

No data found for TURN. Skipping...

$RMED: possibly delisted; no timezone found

No data found for RMED. Skipping...

$ALTR: possibly delisted; no timezone found
$UTX: possibly delisted; no timezone found

No data found for ALTR. Skipping...
No data found for UTX. Skipping...

$WIRE: possibly delisted; no timezone found

No data found for WIRE. Skipping...

$WISA: possibly delisted; no timezone found

No data found for WISA. Skipping...

$LMRKP: possibly delisted; no timezone found

No data found for LMRKP. Skipping...

$APDN: possibly delisted; no timezone found

No data found for APDN. Skipping...

$SINO: possibly delisted; no timezone found
$ZIOP: possibly delisted; no timezone found

No data found for SINO. Skipping...
No data found for ZIOP. Skipping...

$PKI: possibly delisted; no timezone found

No data found for PKI. Skipping...

$IPV: possibly delisted; no timezone found

No data found for IPV. Skipping...

$RTRX: possibly delisted; no timezone found

No data found for RTRX. Skipping...

$BBX: possibly delisted; no timezone found
$HBMD: possibly delisted; no timezone found

No data found for BBX. Skipping...
No data found for HBMD. Skipping...

$SRLP: possibly delisted; no timezone found

No data found for SRLP. Skipping...

$VTNR: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for VTNR. Skipping...

$LEVL: possibly delisted; no timezone found

No data found for LEVL. Skipping...

$EDI: possibly delisted; no timezone found

No data found for EDI. Skipping...

$PQG: possibly delisted; no timezone found

No data found for PQG. Skipping...

$FRGI: possibly delisted; no timezone found

No data found for FRGI. Skipping...

$GSB: possibly delisted; no timezone found

No data found for GSB. Skipping...

$CTEK: possibly delisted; no timezone found

No data found for CTEK. Skipping...

$LACQU: possibly delisted; no timezone found

No data found for LACQU. Skipping...

$AVGOP: possibly delisted; no timezone found

No data found for AVGOP. Skipping...

$IBKCN: possibly delisted; no timezone found

No data found for IBKCN. Skipping...

$PTVCB: possibly delisted; no timezone found

No data found for PTVCB. Skipping...

$FLMN: possibly delisted; no timezone found

No data found for FLMN. Skipping...

$MCEP: possibly delisted; no timezone found
$SRCL: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for MCEP. Skipping...
No data found for SRCL. Skipping...

$WYND: possibly delisted; no timezone found

No data found for WYND. Skipping...

$WWE: possibly delisted; no timezone found

No data found for WWE. Skipping...

$ARGD: possibly delisted; no timezone found

No data found for ARGD. Skipping...

$MDCA: possibly delisted; no timezone found

No data found for MDCA. Skipping...

$PRO: possibly delisted; no timezone found

No data found for PRO. Skipping...

$PUYI: possibly delisted; no timezone found

No data found for PUYI. Skipping...

$SSPKU: possibly delisted; no timezone found

No data found for SSPKU. Skipping...

$NUO: possibly delisted; no timezone found
$RDUS: possibly delisted; no timezone found

No data found for NUO. Skipping...
No data found for RDUS. Skipping...

$WRLSU: possibly delisted; no timezone found
$BBK: possibly delisted; no timezone found

No data found for WRLSU. Skipping...
No data found for BBK. Skipping...

$MDLY: possibly delisted; no timezone found

No data found for MDLY. Skipping...

$CDMO: possibly delisted; no timezone found

No data found for CDMO. Skipping...

$LLIT: possibly delisted; no timezone found

No data found for LLIT. Skipping...

$GHL: possibly delisted; no timezone found

No data found for GHL. Skipping...

$APEN: possibly delisted; no timezone found
$NCB: possibly delisted; no timezone found

No data found for APEN. Skipping...
No data found for NCB. Skipping...

$PEIX: possibly delisted; no timezone found

No data found for PEIX. Skipping...

$ITMR: possibly delisted; no timezone found

No data found for ITMR. Skipping...

$BKCC: possibly delisted; no timezone found

No data found for BKCC. Skipping...

$LPTX: possibly delisted; no timezone found

No data found for LPTX. Skipping...

$VVNT: possibly delisted; no timezone found

No data found for VVNT. Skipping...

$ALACU: possibly delisted; no timezone found

No data found for ALACU. Skipping...

$MODN: possibly delisted; no timezone found

No data found for MODN. Skipping...

$BZM: possibly delisted; no timezone found

No data found for BZM. Skipping...

$IHC: possibly delisted; no timezone found

No data found for IHC. Skipping...

$SFET: possibly delisted; no timezone found

No data found for SFET. Skipping...

$INPX: possibly delisted; no timezone found

No data found for INPX. Skipping...

$JCTCF: possibly delisted; no timezone found

No data found for JCTCF. Skipping...

$NS: possibly delisted; no timezone found

No data found for NS. Skipping...

$MYOS: possibly delisted; no timezone found
$CSU: possibly delisted; no timezone found

No data found for MYOS. Skipping...
No data found for CSU. Skipping...

$LL: possibly delisted; no timezone found

No data found for LL. Skipping...

$KBLMU: possibly delisted; no timezone found

No data found for KBLMU. Skipping...

$IIVI: possibly delisted; no timezone found

No data found for IIVI. Skipping...

$CIDM: possibly delisted; no timezone found

No data found for CIDM. Skipping...

$ATSG: possibly delisted; no timezone found

No data found for ATSG. Skipping...

$AGE: possibly delisted; no timezone found

No data found for AGE. Skipping...

$GWPH: possibly delisted; no timezone found

No data found for GWPH. Skipping...

$AGR: possibly delisted; no timezone found

No data found for AGR. Skipping...

$ARD: possibly delisted; no timezone found

No data found for ARD. Skipping...

$JAN: possibly delisted; no timezone found

No data found for JAN. Skipping...

$SMMC: possibly delisted; no timezone found

No data found for SMMC. Skipping...

$MFL: possibly delisted; no timezone found

No data found for MFL. Skipping...

$MLNX: possibly delisted; no timezone found

No data found for MLNX. Skipping...

$HMHC: possibly delisted; no timezone found

No data found for HMHC. Skipping...

$UN: possibly delisted; no timezone found

No data found for UN. Skipping...

$LONE: possibly delisted; no timezone found

No data found for LONE. Skipping...

$SMLP: possibly delisted; no timezone found

No data found for SMLP. Skipping...

$AMEH: possibly delisted; no timezone found

No data found for AMEH. Skipping...

$NETE: possibly delisted; no timezone found

No data found for NETE. Skipping...

$CEO: possibly delisted; no timezone found

No data found for CEO. Skipping...

$SCS: possibly delisted; no timezone found

No data found for SCS. Skipping...

$GRTS: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for GRTS. Skipping...

$MBINP: possibly delisted; no timezone found

No data found for MBINP. Skipping...

$SAL: possibly delisted; no timezone found

No data found for SAL. Skipping...

$XRF: possibly delisted; no timezone found

No data found for XRF. Skipping...

$CDK: possibly delisted; no timezone found

No data found for CDK. Skipping...

$REPH: possibly delisted; no timezone found

No data found for REPH. Skipping...

$MIC: possibly delisted; no timezone found

No data found for MIC. Skipping...

$PSTI: possibly delisted; no timezone found

No data found for PSTI. Skipping...

$NURO: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for NURO. Skipping...

$OPB: possibly delisted; no timezone found

No data found for OPB. Skipping...

$CEN: possibly delisted; no timezone found
$SAVE: possibly delisted; no timezone found

No data found for CEN. Skipping...
No data found for SAVE. Skipping...

$KAMN: possibly delisted; no timezone found

No data found for KAMN. Skipping...

$BSQR: possibly delisted; no timezone found

No data found for BSQR. Skipping...

$MRIN: possibly delisted; no timezone found

No data found for MRIN. Skipping...

$OSMT: possibly delisted; no timezone found

No data found for OSMT. Skipping...

$OSN: possibly delisted; no timezone found
$CFB: possibly delisted; no timezone found

No data found for OSN. Skipping...
No data found for CFB. Skipping...

$GPAQ: possibly delisted; no timezone found

No data found for GPAQ. Skipping...

$AMHCU: possibly delisted; no timezone found

No data found for AMHCU. Skipping...

$CNTG: possibly delisted; no timezone found

No data found for CNTG. Skipping...

$LCAHU: possibly delisted; no timezone found
$FORK: possibly delisted; no timezone found

No data found for LCAHU. Skipping...
No data found for FORK. Skipping...

$JAX: possibly delisted; no timezone found

No data found for JAX. Skipping...

$JCP: possibly delisted; no timezone found

No data found for JCP. Skipping...

$MGI: possibly delisted; no timezone found
$MEDS: possibly delisted; no timezone found

No data found for MGI. Skipping...
No data found for MEDS. Skipping...

$JBT: possibly delisted; no timezone found

No data found for JBT. Skipping...

$CYCC: possibly delisted; no timezone found

No data found for CYCC. Skipping...

$AGS: possibly delisted; no timezone found

No data found for AGS. Skipping...

$DEACU: possibly delisted; no timezone found

No data found for DEACU. Skipping...

$AEL: possibly delisted; no timezone found

No data found for AEL. Skipping...

$ACRX: possibly delisted; no timezone found

No data found for ACRX. Skipping...

$CIFS: possibly delisted; no timezone found

No data found for CIFS. Skipping...

$DXB: possibly delisted; no timezone found

No data found for DXB. Skipping...

$LM: possibly delisted; no timezone found

No data found for LM. Skipping...

$INSU: possibly delisted; no timezone found

No data found for INSU. Skipping...

$QRTEA: possibly delisted; no timezone found

No data found for QRTEA. Skipping...

$TFFP: possibly delisted; no timezone found

No data found for TFFP. Skipping...

$BDGE: possibly delisted; no timezone found

No data found for BDGE. Skipping...

$STL: possibly delisted; no timezone found
$NR: possibly delisted; no timezone found

No data found for STL. Skipping...
No data found for NR. Skipping...

$LAZY: possibly delisted; no timezone found

No data found for LAZY. Skipping...

$AKG: possibly delisted; no timezone found

No data found for AKG. Skipping...

$GHIVU: possibly delisted; no timezone found
$ECCB: possibly delisted; no timezone found

No data found for GHIVU. Skipping...
No data found for ECCB. Skipping...

$HCR: possibly delisted; no timezone found

No data found for HCR. Skipping...

$DPHCU: possibly delisted; no timezone found

No data found for DPHCU. Skipping...

$ODP: possibly delisted; no timezone found

No data found for ODP. Skipping...

$BXS: possibly delisted; no timezone found

No data found for BXS. Skipping...

$FDUSZ: possibly delisted; no timezone found

No data found for FDUSZ. Skipping...

$CHPMU: possibly delisted; no timezone found
$IMBI: possibly delisted; no timezone found

No data found for CHPMU. Skipping...
No data found for IMBI. Skipping...

$AERI: possibly delisted; no timezone found

No data found for AERI. Skipping...

$FNCB: possibly delisted; no timezone found

No data found for FNCB. Skipping...

$BRMK: possibly delisted; no timezone found

No data found for BRMK. Skipping...

$YUMA: possibly delisted; no timezone found

No data found for YUMA. Skipping...

$ABTX: possibly delisted; no timezone found

No data found for ABTX. Skipping...

$ANAT: possibly delisted; no timezone found

No data found for ANAT. Skipping...

$UZA: possibly delisted; no timezone found

No data found for UZA. Skipping...

$PJH: possibly delisted; no timezone found

No data found for PJH. Skipping...

$EQM: possibly delisted; no timezone found

No data found for EQM. Skipping...

$NFINU: possibly delisted; no timezone found

No data found for NFINU. Skipping...

$ERA: possibly delisted; no timezone found

No data found for ERA. Skipping...

$ALUS: possibly delisted; no timezone found

No data found for ALUS. Skipping...

$APEX: possibly delisted; no timezone found

No data found for APEX. Skipping...

$GMLP: possibly delisted; no timezone found

No data found for GMLP. Skipping...

$MJCO: possibly delisted; no timezone found

No data found for MJCO. Skipping...

$UBP: possibly delisted; no timezone found

No data found for UBP. Skipping...

$MDLX: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for MDLX. Skipping...

$FPRX: possibly delisted; no timezone found

No data found for FPRX. Skipping...

$NGHCZ: possibly delisted; no timezone found

No data found for NGHCZ. Skipping...

$FBMS: possibly delisted; no timezone found

No data found for FBMS. Skipping...

$BAF: possibly delisted; no timezone found

No data found for BAF. Skipping...

$VJET: possibly delisted; no timezone found

No data found for VJET. Skipping...

$MSON: possibly delisted; no timezone found

No data found for MSON. Skipping...

$TPTX: possibly delisted; no timezone found

No data found for TPTX. Skipping...

$IRL: possibly delisted; no timezone found

No data found for IRL. Skipping...

$ONVO: possibly delisted; no timezone found

No data found for ONVO. Skipping...

$ERYP: possibly delisted; no timezone found

No data found for ERYP. Skipping...

$LCA: possibly delisted; no timezone found

No data found for LCA. Skipping...

$TUFN: possibly delisted; no timezone found

No data found for TUFN. Skipping...

$BIOC: possibly delisted; no timezone found

No data found for BIOC. Skipping...

$GRA: possibly delisted; no timezone found

No data found for GRA. Skipping...

$PPD: possibly delisted; no timezone found
$FREQ: possibly delisted; no timezone found

No data found for PPD. Skipping...
No data found for FREQ. Skipping...

$CORR: possibly delisted; no timezone found

No data found for CORR. Skipping...

$SNSS: possibly delisted; no timezone found

No data found for SNSS. Skipping...

$HKIB: possibly delisted; no timezone found

No data found for HKIB. Skipping...

$CORE: possibly delisted; no timezone found

No data found for CORE. Skipping...

$OBLN: possibly delisted; no timezone found

No data found for OBLN. Skipping...

$EFF: possibly delisted; no timezone found
$KIQ: possibly delisted; no timezone found

No data found for EFF. Skipping...
No data found for KIQ. Skipping...

$NGHCO: possibly delisted; no timezone found

No data found for NGHCO. Skipping...

$ALBO: possibly delisted; no timezone found

No data found for ALBO. Skipping...

$LSXMK: possibly delisted; no timezone found

No data found for LSXMK. Skipping...

$ALAC: possibly delisted; no timezone found
$VOXX: possibly delisted; no timezone found

No data found for ALAC. Skipping...
No data found for VOXX. Skipping...

$ZIXI: possibly delisted; no timezone found

No data found for ZIXI. Skipping...

$NFIN: possibly delisted; no timezone found
$XBIOW: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for NFIN. Skipping...
No data found for XBIOW. Skipping...

$SPAR: possibly delisted; no timezone found

No data found for SPAR. Skipping...

$CHMA: possibly delisted; no timezone found

No data found for CHMA. Skipping...

$WLL: possibly delisted; no timezone found

No data found for WLL. Skipping...

$IOTS: possibly delisted; no timezone found

No data found for IOTS. Skipping...

$WNS: possibly delisted; no timezone found

No data found for WNS. Skipping...

$PLAN: possibly delisted; no timezone found

No data found for PLAN. Skipping...

$UZC: possibly delisted; no timezone found

No data found for UZC. Skipping...

$CMCTP: possibly delisted; no timezone found

No data found for CMCTP. Skipping...

$PER: possibly delisted; no timezone found

No data found for PER. Skipping...

$PBCTP: possibly delisted; no timezone found

No data found for PBCTP. Skipping...

$SGOC: possibly delisted; no timezone found

No data found for SGOC. Skipping...

$IID: possibly delisted; no timezone found

No data found for IID. Skipping...

$CYOU: possibly delisted; no timezone found

No data found for CYOU. Skipping...

$PDCO: possibly delisted; no timezone found

No data found for PDCO. Skipping...

$POPE: possibly delisted; no timezone found

No data found for POPE. Skipping...

$AMRB: possibly delisted; no timezone found

No data found for AMRB. Skipping...

$AZRX: possibly delisted; no timezone found

No data found for AZRX. Skipping...

$BRPAU: possibly delisted; no timezone found

No data found for BRPAU. Skipping...

$AEY: possibly delisted; no timezone found

No data found for AEY. Skipping...

$VEC: possibly delisted; no timezone found

No data found for VEC. Skipping...

$HNW: possibly delisted; no timezone found

No data found for HNW. Skipping...

$CUTR: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for CUTR. Skipping...

$CYBE: possibly delisted; no timezone found

No data found for CYBE. Skipping...

$CERN: possibly delisted; no timezone found

No data found for CERN. Skipping...

$ZEN: possibly delisted; no timezone found
$MFO: possibly delisted; no timezone found

No data found for ZEN. Skipping...
No data found for MFO. Skipping...

$OTEL: possibly delisted; no timezone found

No data found for OTEL. Skipping...

$MDP: possibly delisted; no timezone found

No data found for MDP. Skipping...

$HTGM: possibly delisted; no timezone found
$CHK: possibly delisted; no timezone found

No data found for HTGM. Skipping...
No data found for CHK. Skipping...

$PFBI: possibly delisted; no timezone found

No data found for PFBI. Skipping...

$TDE: possibly delisted; no timezone found
$BFIN: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for TDE. Skipping...
No data found for BFIN. Skipping...

$YY: possibly delisted; no timezone found

No data found for YY. Skipping...

$TGI: possibly delisted; no timezone found

No data found for TGI. Skipping...

$TCON: possibly delisted; no timezone found

No data found for TCON. Skipping...

$HTY: possibly delisted; no timezone found

No data found for HTY. Skipping...

$SBT: possibly delisted; no timezone found

No data found for SBT. Skipping...

$CRHM: possibly delisted; no timezone found

No data found for CRHM. Skipping...

$RUTH: possibly delisted; no timezone found

No data found for RUTH. Skipping...

$PTSI: possibly delisted; no timezone found

No data found for PTSI. Skipping...

$CEL: possibly delisted; no timezone found

No data found for CEL. Skipping...

$TTNP: possibly delisted; no timezone found

No data found for TTNP. Skipping...

$MHE: possibly delisted; no timezone found
$CEM: possibly delisted; no timezone found

No data found for MHE. Skipping...
No data found for CEM. Skipping...

$TGH: possibly delisted; no timezone found

No data found for TGH. Skipping...

$NBRV: possibly delisted; no timezone found

No data found for NBRV. Skipping...

$NBSE: possibly delisted; no timezone found

No data found for NBSE. Skipping...

$ATHX: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for ATHX. Skipping...

$AQUA: possibly delisted; no timezone found

No data found for AQUA. Skipping...

$GRUB: possibly delisted; no timezone found

No data found for GRUB. Skipping...

$BOMN: possibly delisted; no timezone found

No data found for BOMN. Skipping...

$SMM: possibly delisted; no timezone found

No data found for SMM. Skipping...

$ACER: possibly delisted; no timezone found

No data found for ACER. Skipping...

$HWCPL: possibly delisted; no timezone found

No data found for HWCPL. Skipping...

$MNTA: possibly delisted; no timezone found

No data found for MNTA. Skipping...

$APY: possibly delisted; no timezone found

No data found for APY. Skipping...

$MEET: possibly delisted; no timezone found

No data found for MEET. Skipping...

$JCS: possibly delisted; no timezone found

No data found for JCS. Skipping...

$TOCA: possibly delisted; no timezone found

No data found for TOCA. Skipping...

$AFT: possibly delisted; no timezone found

No data found for AFT. Skipping...

$FBM: possibly delisted; no timezone found

No data found for FBM. Skipping...

$AFC: possibly delisted; no timezone found

No data found for AFC. Skipping...

$GENE: possibly delisted; no timezone found

No data found for GENE. Skipping...

$XIN: possibly delisted; no timezone found

No data found for XIN. Skipping...

$EXPCU: possibly delisted; no timezone found

No data found for EXPCU. Skipping...

$CLUB: possibly delisted; no timezone found

No data found for CLUB. Skipping...

$SWT: possibly delisted; no timezone found

No data found for SWT. Skipping...

$STXB: possibly delisted; no timezone found

No data found for STXB. Skipping...

$QRTEB: possibly delisted; no timezone found

No data found for QRTEB. Skipping...

$LN: possibly delisted; no timezone found

No data found for LN. Skipping...

$CPTAG: possibly delisted; no timezone found

No data found for CPTAG. Skipping...

$IKNX: possibly delisted; no timezone found

No data found for IKNX. Skipping...

$TRTN: possibly delisted; no timezone found

No data found for TRTN. Skipping...

$ARPO: possibly delisted; no timezone found

No data found for ARPO. Skipping...

$DCPH: possibly delisted; no timezone found

No data found for DCPH. Skipping...

$PGRE: possibly delisted; no timezone found

No data found for PGRE. Skipping...

$BXG: possibly delisted; no timezone found

No data found for BXG. Skipping...

$MOHO: possibly delisted; no timezone found

No data found for MOHO. Skipping...

$PHT: possibly delisted; no timezone found

No data found for PHT. Skipping...

$PKO: possibly delisted; no timezone found

No data found for PKO. Skipping...

$SILV: possibly delisted; no timezone found

No data found for SILV. Skipping...

$NSEC: possibly delisted; no timezone found

No data found for NSEC. Skipping...

$USAP: possibly delisted; no timezone found

No data found for USAP. Skipping...

$BECN: possibly delisted; no timezone found

No data found for BECN. Skipping...

$WBAI: possibly delisted; no timezone found
$LYL: possibly delisted; no timezone found

No data found for WBAI. Skipping...
No data found for LYL. Skipping...

$BBI: possibly delisted; no timezone found

No data found for BBI. Skipping...

$CDOR: possibly delisted; no timezone found

No data found for CDOR. Skipping...

$IPG: possibly delisted; no timezone found

No data found for IPG. Skipping...

$NGHCN: possibly delisted; no timezone found

No data found for NGHCN. Skipping...

$LOV: possibly delisted; no timezone found

No data found for LOV. Skipping...

$PWOD: possibly delisted; no timezone found

No data found for PWOD. Skipping...

$NUM: possibly delisted; no timezone found

No data found for NUM. Skipping...

$PPR: possibly delisted; no timezone found

No data found for PPR. Skipping...

$GSS: possibly delisted; no timezone found

No data found for GSS. Skipping...

$ROIC: possibly delisted; no timezone found

No data found for ROIC. Skipping...

$BLU: possibly delisted; no timezone found

No data found for BLU. Skipping...

$CDAY: possibly delisted; no timezone found

No data found for CDAY. Skipping...

$ARAV: possibly delisted; no timezone found

No data found for ARAV. Skipping...

$CDEV: possibly delisted; no timezone found

No data found for CDEV. Skipping...

$PINC: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for PINC. Skipping...

$PWFL: possibly delisted; no timezone found

No data found for PWFL. Skipping...

$COUP: possibly delisted; no timezone found

No data found for COUP. Skipping...

$CHPM: possibly delisted; no timezone found

No data found for CHPM. Skipping...

$ORSNU: possibly delisted; no timezone found

No data found for ORSNU. Skipping...

$RCA: possibly delisted; no timezone found

No data found for RCA. Skipping...

$ALGR: possibly delisted; no timezone found

No data found for ALGR. Skipping...

$EIGR: possibly delisted; no timezone found

No data found for EIGR. Skipping...

$PLL: possibly delisted; no timezone found

No data found for PLL. Skipping...

$YGYI: possibly delisted; no timezone found

No data found for YGYI. Skipping...

$QADA: possibly delisted; no timezone found

No data found for QADA. Skipping...

$EVM: possibly delisted; no timezone found

No data found for EVM. Skipping...

$NEP: possibly delisted; no timezone found

No data found for NEP. Skipping...

$PIXY: possibly delisted; no timezone found

No data found for PIXY. Skipping...

$NID: possibly delisted; no timezone found

No data found for NID. Skipping...

$CTT: possibly delisted; no timezone found

No data found for CTT. Skipping...

$HA: possibly delisted; no timezone found

No data found for HA. Skipping...

$DRE: possibly delisted; no timezone found

No data found for DRE. Skipping...

$VAM: possibly delisted; no timezone found

No data found for VAM. Skipping...

$PTNR: possibly delisted; no timezone found

No data found for PTNR. Skipping...

$BSMX: possibly delisted; no timezone found

No data found for BSMX. Skipping...

$FEN: possibly delisted; no timezone found

No data found for FEN. Skipping...

$GLIBP: possibly delisted; no timezone found

No data found for GLIBP. Skipping...

$KDMN: possibly delisted; no timezone found

No data found for KDMN. Skipping...

$MTL: possibly delisted; no timezone found

No data found for MTL. Skipping...

$MUH: possibly delisted; no timezone found

No data found for MUH. Skipping...

$ADES: possibly delisted; no timezone found
$VEDL: possibly delisted; no timezone found

No data found for ADES. Skipping...
No data found for VEDL. Skipping...

$ATCO: possibly delisted; no timezone found
$STFC: possibly delisted; no timezone found

No data found for ATCO. Skipping...
No data found for STFC. Skipping...

$CLR: possibly delisted; no timezone found
$ATV: possibly delisted; no timezone found

No data found for CLR. Skipping...
No data found for ATV. Skipping...

$HMNF: possibly delisted; no timezone found

No data found for HMNF. Skipping...

$CYRN: possibly delisted; no timezone found

No data found for CYRN. Skipping...

$FRG: possibly delisted; no timezone found

No data found for FRG. Skipping...

$IBTX: possibly delisted; no timezone found

No data found for IBTX. Skipping...

$MIXT: possibly delisted; no timezone found

No data found for MIXT. Skipping...

$TCP: possibly delisted; no timezone found
$AXU: possibly delisted; no timezone found

No data found for TCP. Skipping...
No data found for AXU. Skipping...

$TBC: possibly delisted; no timezone found

No data found for TBC. Skipping...

$IPHI: possibly delisted; no timezone found

No data found for IPHI. Skipping...

$TCF: possibly delisted; no timezone found

No data found for TCF. Skipping...

$ESTE: possibly delisted; no timezone found

No data found for ESTE. Skipping...

$RNDB: possibly delisted; no timezone found

No data found for RNDB. Skipping...

$MMX: possibly delisted; no timezone found

No data found for MMX. Skipping...

$GLYC: possibly delisted; no timezone found

No data found for GLYC. Skipping...

$SGH: possibly delisted; no timezone found
$SIC: possibly delisted; no timezone found

No data found for SGH. Skipping...
No data found for SIC. Skipping...

$FCAU: possibly delisted; no timezone found

No data found for FCAU. Skipping...

$AHPI: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for AHPI. Skipping...

$FSB: possibly delisted; no timezone found

No data found for FSB. Skipping...

$HCCO: possibly delisted; no timezone found

No data found for HCCO. Skipping...

$TLI: possibly delisted; no timezone found

No data found for TLI. Skipping...

$AVH: possibly delisted; no timezone found

No data found for AVH. Skipping...

$HCAP: possibly delisted; no timezone found

No data found for HCAP. Skipping...

$MUI: possibly delisted; no timezone found

No data found for MUI. Skipping...

$JPT: possibly delisted; no timezone found

No data found for JPT. Skipping...

$THBR: possibly delisted; no timezone found

No data found for THBR. Skipping...

$THCA: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for THCA. Skipping...

$FEO: possibly delisted; no timezone found

No data found for FEO. Skipping...

$PCOM: possibly delisted; no timezone found

No data found for PCOM. Skipping...

$CTB: possibly delisted; no timezone found

No data found for CTB. Skipping...

$MYJ: possibly delisted; no timezone found

No data found for MYJ. Skipping...

$HDS: possibly delisted; no timezone found
$HGH: possibly delisted; no timezone found

No data found for HDS. Skipping...
No data found for HGH. Skipping...

$SAFM: possibly delisted; no timezone found

No data found for SAFM. Skipping...

$AZUL: possibly delisted; no timezone found

No data found for AZUL. Skipping...

$KL: possibly delisted; no timezone found
$HONE: possibly delisted; no timezone found

No data found for KL. Skipping...
No data found for HONE. Skipping...

$DSSI: possibly delisted; no timezone found

No data found for DSSI. Skipping...

$PRNB: possibly delisted; no timezone found

No data found for PRNB. Skipping...

$KBLM: possibly delisted; no timezone found

No data found for KBLM. Skipping...

$LSI: possibly delisted; no timezone found

No data found for LSI. Skipping...

$SRRA: possibly delisted; no timezone found

No data found for SRRA. Skipping...

$LEJU: possibly delisted; no timezone found

No data found for LEJU. Skipping...

$BKEP: possibly delisted; no timezone found

No data found for BKEP. Skipping...

$BOKFL: possibly delisted; no timezone found

No data found for BOKFL. Skipping...

$NHA: possibly delisted; no timezone found

No data found for NHA. Skipping...

$AIMT: possibly delisted; no timezone found

No data found for AIMT. Skipping...

$NTEC: possibly delisted; no timezone found

No data found for NTEC. Skipping...

$AIMC: possibly delisted; no timezone found

No data found for AIMC. Skipping...

$GMS: possibly delisted; no timezone found

No data found for GMS. Skipping...

$CRSAU: possibly delisted; no timezone found

No data found for CRSAU. Skipping...

$GOL: possibly delisted; no timezone found

No data found for GOL. Skipping...

$PLM: possibly delisted; no timezone found

No data found for PLM. Skipping...

$SBOW: possibly delisted; no timezone found

No data found for SBOW. Skipping...

$EAE: possibly delisted; no timezone found

No data found for EAE. Skipping...

$ITI: possibly delisted; no timezone found

No data found for ITI. Skipping...

$RVNC: possibly delisted; no timezone found

No data found for RVNC. Skipping...

$SPRT: possibly delisted; no timezone found

No data found for SPRT. Skipping...

$SUMR: possibly delisted; no timezone found

No data found for SUMR. Skipping...

$PAVMW: possibly delisted; no timezone found

No data found for PAVMW. Skipping...

$RBS: possibly delisted; no timezone found

No data found for RBS. Skipping...

$GOODM: possibly delisted; no timezone found
$SBLKZ: possibly delisted; no timezone found

No data found for GOODM. Skipping...
No data found for SBLKZ. Skipping...

$CATM: possibly delisted; no timezone found

No data found for CATM. Skipping...

$LHC: possibly delisted; no timezone found

No data found for LHC. Skipping...

$COWN: possibly delisted; no timezone found

No data found for COWN. Skipping...

$SBBP: possibly delisted; no timezone found

No data found for SBBP. Skipping...

$ARCH: possibly delisted; no timezone found

No data found for ARCH. Skipping...

$GTS: possibly delisted; no timezone found

No data found for GTS. Skipping...

$PTI: possibly delisted; no timezone found

No data found for PTI. Skipping...

$WPG: possibly delisted; no timezone found

No data found for WPG. Skipping...

$CTAA: possibly delisted; no timezone found

No data found for CTAA. Skipping...

$DCAR: possibly delisted; no timezone found

No data found for DCAR. Skipping...

$TREC: possibly delisted; no timezone found

No data found for TREC. Skipping...

$ALIM: possibly delisted; no timezone found

No data found for ALIM. Skipping...

$NRZ: possibly delisted; no timezone found

No data found for NRZ. Skipping...

$PYN: possibly delisted; no timezone found

No data found for PYN. Skipping...

$IVC: possibly delisted; no timezone found

No data found for IVC. Skipping...

$EPIX: possibly delisted; no timezone found
$LOACU: possibly delisted; no timezone found

No data found for EPIX. Skipping...
No data found for LOACU. Skipping...

$MDJH: possibly delisted; no timezone found

No data found for MDJH. Skipping...

$ENBL: possibly delisted; no timezone found

No data found for ENBL. Skipping...

$PRTY: possibly delisted; no timezone found

No data found for PRTY. Skipping...

$PGNX: possibly delisted; no timezone found
$SPPI: possibly delisted; no timezone found

No data found for PGNX. Skipping...
No data found for SPPI. Skipping...

$MCMJ: possibly delisted; no timezone found

No data found for MCMJ. Skipping...

$SNMP: possibly delisted; no timezone found

No data found for SNMP. Skipping...

$PRCP: possibly delisted; no timezone found

No data found for PRCP. Skipping...

$DMTK: possibly delisted; no timezone found

No data found for DMTK. Skipping...

$QADB: possibly delisted; no timezone found

No data found for QADB. Skipping...

$BSD: possibly delisted; no timezone found

No data found for BSD. Skipping...

$NFH: possibly delisted; no timezone found

No data found for NFH. Skipping...

$NES: possibly delisted; no timezone found

No data found for NES. Skipping...

$AGBA: possibly delisted; no timezone found

No data found for AGBA. Skipping...

$CONN: possibly delisted; no timezone found

No data found for CONN. Skipping...

$PROS: possibly delisted; no timezone found

No data found for PROS. Skipping...

$TERP: possibly delisted; no timezone found

No data found for TERP. Skipping...

$DSPG: possibly delisted; no timezone found
$LUMO: possibly delisted; no timezone found

No data found for DSPG. Skipping...
No data found for LUMO. Skipping...

$VSTO: possibly delisted; no timezone found

No data found for VSTO. Skipping...

$NMFX: possibly delisted; no timezone found

No data found for NMFX. Skipping...

$HIBB: possibly delisted; no timezone found

No data found for HIBB. Skipping...

$BRKL: possibly delisted; no timezone found
$GSLD: possibly delisted; no timezone found

No data found for BRKL. Skipping...
No data found for GSLD. Skipping...

$DRQ: possibly delisted; no timezone found

No data found for DRQ. Skipping...

$TTM: possibly delisted; no timezone found

No data found for TTM. Skipping...

$ZAGG: possibly delisted; no timezone found
$VMM: possibly delisted; no timezone found

No data found for ZAGG. Skipping...
No data found for VMM. Skipping...

$NRGX: possibly delisted; no timezone found

No data found for NRGX. Skipping...

$BCEL: possibly delisted; no timezone found

No data found for BCEL. Skipping...

$STSA: possibly delisted; no timezone found

No data found for STSA. Skipping...

$RLGY: possibly delisted; no timezone found

No data found for RLGY. Skipping...

$FI: possibly delisted; no timezone found

No data found for FI. Skipping...

$HHR: possibly delisted; no timezone found

No data found for HHR. Skipping...

$BVSN: possibly delisted; no timezone found

No data found for BVSN. Skipping...

$VERB: possibly delisted; no timezone found
$VCF: possibly delisted; no timezone found

No data found for VERB. Skipping...
No data found for VCF. Skipping...

$CNFR: possibly delisted; no timezone found

No data found for CNFR. Skipping...

$PS: possibly delisted; no timezone found

No data found for PS. Skipping...

$ACAMU: possibly delisted; no timezone found

No data found for ACAMU. Skipping...

$JDD: possibly delisted; no timezone found

No data found for JDD. Skipping...

$FPL: possibly delisted; no timezone found

No data found for FPL. Skipping...

$DEAC: possibly delisted; no timezone found

No data found for DEAC. Skipping...

$MCF: possibly delisted; no timezone found

No data found for MCF. Skipping...

$GLUU: possibly delisted; no timezone found

No data found for GLUU. Skipping...

$ZSAN: possibly delisted; no timezone found

No data found for ZSAN. Skipping...

$TCS: possibly delisted; no timezone found

No data found for TCS. Skipping...

$CEMI: possibly delisted; no timezone found
$GFNCP: possibly delisted; no timezone found

No data found for CEMI. Skipping...
No data found for GFNCP. Skipping...

$DRNA: possibly delisted; no timezone found

No data found for DRNA. Skipping...

$DEX: possibly delisted; no timezone found

No data found for DEX. Skipping...

$POAI: possibly delisted; no timezone found

No data found for POAI. Skipping...

$MOR: possibly delisted; no timezone found

No data found for MOR. Skipping...

$QUMU: possibly delisted; no timezone found

No data found for QUMU. Skipping...

$LOGM: possibly delisted; no timezone found

No data found for LOGM. Skipping...

$JEMD: possibly delisted; no timezone found
$NUVA: possibly delisted; no timezone found

No data found for JEMD. Skipping...
No data found for NUVA. Skipping...

$AMAG: possibly delisted; no timezone found

No data found for AMAG. Skipping...

$CCH: possibly delisted; no timezone found

No data found for CCH. Skipping...

$VBLT: possibly delisted; no timezone found

No data found for VBLT. Skipping...

$JNPR: possibly delisted; no timezone found

No data found for JNPR. Skipping...

$AUG: possibly delisted; no timezone found
$MBT: possibly delisted; no timezone found

No data found for AUG. Skipping...
No data found for MBT. Skipping...

$PE: possibly delisted; no timezone found

No data found for PE. Skipping...

$BPOPN: possibly delisted; no timezone found

No data found for BPOPN. Skipping...

$AVYA: possibly delisted; no timezone found

No data found for AVYA. Skipping...

$LVGO: possibly delisted; no timezone found
$RPAI: possibly delisted; no timezone found

No data found for LVGO. Skipping...
No data found for RPAI. Skipping...

$TCRW: possibly delisted; no timezone found

No data found for TCRW. Skipping...

$AAU: possibly delisted; no timezone found

No data found for AAU. Skipping...

$ADRO: possibly delisted; no timezone found

No data found for ADRO. Skipping...

$METX: possibly delisted; no timezone found

No data found for METX. Skipping...

$THCB: possibly delisted; no timezone found

No data found for THCB. Skipping...

$FOCS: possibly delisted; no timezone found

No data found for FOCS. Skipping...

$LORL: possibly delisted; no timezone found

No data found for LORL. Skipping...

$SSY: possibly delisted; no timezone found

No data found for SSY. Skipping...

$EXPR: possibly delisted; no timezone found

No data found for EXPR. Skipping...

$ALE: possibly delisted; no timezone found

No data found for ALE. Skipping...

$AVCO: possibly delisted; no timezone found

No data found for AVCO. Skipping...

$HT: possibly delisted; no timezone found
$CTV: possibly delisted; no timezone found

No data found for HT. Skipping...
No data found for CTV. Skipping...

$JFKKU: possibly delisted; no timezone found

No data found for JFKKU. Skipping...

$ESBK: possibly delisted; no timezone found

No data found for ESBK. Skipping...

$FBSS: possibly delisted; no timezone found

No data found for FBSS. Skipping...

$INS: possibly delisted; no timezone found

No data found for INS. Skipping...

$EXD: possibly delisted; no timezone found

No data found for EXD. Skipping...

$IMH: possibly delisted; no timezone found
$TPIC: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for IMH. Skipping...
No data found for TPIC. Skipping...

$RZA: possibly delisted; no timezone found

No data found for RZA. Skipping...

$ELAT: possibly delisted; no timezone found

No data found for ELAT. Skipping...

$OPESU: possibly delisted; no timezone found

No data found for OPESU. Skipping...

$NGM: possibly delisted; no timezone found
$LLNW: possibly delisted; no timezone found

No data found for NGM. Skipping...

$GMHI: possibly delisted; no timezone found

No data found for LLNW. Skipping...
No data found for GMHI. Skipping...

$ALPN: possibly delisted; no timezone found
$PNF: possibly delisted; no timezone found

No data found for ALPN. Skipping...
No data found for PNF. Skipping...

$FNHC: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for FNHC. Skipping...

$BSE: possibly delisted; no timezone found

No data found for BSE. Skipping...

$AEZS: possibly delisted; no timezone found

No data found for AEZS. Skipping...

$GLT: possibly delisted; no timezone found

No data found for GLT. Skipping...

$PECK: possibly delisted; no timezone found

No data found for PECK. Skipping...

$INSUU: possibly delisted; no timezone found

No data found for INSUU. Skipping...

$NAKD: possibly delisted; no timezone found

No data found for NAKD. Skipping...

$KERN: possibly delisted; no timezone found

No data found for KERN. Skipping...

$PZC: possibly delisted; no timezone found
$PYX: possibly delisted; no timezone found

No data found for PZC. Skipping...
No data found for PYX. Skipping...

$ZGYHU: possibly delisted; no timezone found

No data found for ZGYHU. Skipping...

$VAPO: possibly delisted; no timezone found
$NVIV: possibly delisted; no timezone found

No data found for VAPO. Skipping...
No data found for NVIV. Skipping...

$BPFH: possibly delisted; no timezone found

No data found for BPFH. Skipping...

$NVFY: possibly delisted; no timezone found

No data found for NVFY. Skipping...

$FLIR: possibly delisted; no timezone found

No data found for FLIR. Skipping...

$SRDX: possibly delisted; no timezone found

No data found for SRDX. Skipping...

$HYRE: possibly delisted; no timezone found

No data found for HYRE. Skipping...

$ENZ: possibly delisted; no timezone found

No data found for ENZ. Skipping...

$BGFV: possibly delisted; no timezone found

No data found for BGFV. Skipping...

$TBLTW: possibly delisted; no timezone found

No data found for TBLTW. Skipping...

$GRNVU: possibly delisted; no timezone found

No data found for GRNVU. Skipping...

$ANSS: possibly delisted; no timezone found

No data found for ANSS. Skipping...

$FRAN: possibly delisted; no timezone found

No data found for FRAN. Skipping...

$UTX#: possibly delisted; no timezone found

No data found for UTX#. Skipping...

$SPKEP: possibly delisted; no timezone found
$RLH: possibly delisted; no timezone found

No data found for SPKEP. Skipping...
No data found for RLH. Skipping...

$EAB: possibly delisted; no timezone found

No data found for EAB. Skipping...

$MMAC: possibly delisted; no timezone found

No data found for MMAC. Skipping...

$NSL: possibly delisted; no timezone found
$MOXC: possibly delisted; no timezone found

No data found for NSL. Skipping...
No data found for MOXC. Skipping...

$PRTK: possibly delisted; no timezone found

No data found for PRTK. Skipping...

$PETQ: possibly delisted; no timezone found

No data found for PETQ. Skipping...

$APTS: possibly delisted; no timezone found

No data found for APTS. Skipping...

$EIDX: possibly delisted; no timezone found

No data found for EIDX. Skipping...

$CTLT: possibly delisted; no timezone found

No data found for CTLT. Skipping...

$CSII: possibly delisted; no timezone found

No data found for CSII. Skipping...

$AGBAU: possibly delisted; no timezone found
$VTIQ: possibly delisted; no timezone found

No data found for AGBAU. Skipping...
No data found for VTIQ. Skipping...

$BSA: possibly delisted; no timezone found
$NEV: possibly delisted; no timezone found

No data found for BSA. Skipping...
No data found for NEV. Skipping...

$SYNC: possibly delisted; no timezone found

No data found for SYNC. Skipping...

$GLG: possibly delisted; no timezone found

No data found for GLG. Skipping...

$CVCY: possibly delisted; no timezone found

No data found for CVCY. Skipping...

$ARYA: possibly delisted; no timezone found

No data found for ARYA. Skipping...

$EVK: possibly delisted; no timezone found

No data found for EVK. Skipping...

$FEYE: possibly delisted; no timezone found

No data found for FEYE. Skipping...

$RTN: possibly delisted; no timezone found

No data found for RTN. Skipping...

$WRLS: possibly delisted; no timezone found

No data found for WRLS. Skipping...

$GTHX: possibly delisted; no timezone found
$JOBS: possibly delisted; no timezone found

No data found for GTHX. Skipping...
No data found for JOBS. Skipping...

$VCRA: possibly delisted; no timezone found

No data found for VCRA. Skipping...

$NVRO: possibly delisted; no timezone found

No data found for NVRO. Skipping...

$DCUE: possibly delisted; no timezone found

No data found for DCUE. Skipping...

$GBL: possibly delisted; no timezone found

No data found for GBL. Skipping...

$NHF: possibly delisted; no timezone found

No data found for NHF. Skipping...

$BFYT: possibly delisted; no timezone found
$HEP: possibly delisted; no timezone found

No data found for BFYT. Skipping...
No data found for HEP. Skipping...

$HVBC: possibly delisted; no timezone found

No data found for HVBC. Skipping...

$BCEI: possibly delisted; no timezone found

No data found for BCEI. Skipping...

$AFGH: possibly delisted; no timezone found

No data found for AFGH. Skipping...

$AJRD: possibly delisted; no timezone found
$MZA: possibly delisted; no timezone found

No data found for AJRD. Skipping...
No data found for MZA. Skipping...

$CTR: possibly delisted; no timezone found

No data found for CTR. Skipping...

$DNKN: possibly delisted; no timezone found

No data found for DNKN. Skipping...

$FANH: possibly delisted; no timezone found

No data found for FANH. Skipping...

$ZVO: possibly delisted; no timezone found
$ACY: possibly delisted; no timezone found

No data found for ZVO. Skipping...
No data found for ACY. Skipping...

$JPS: possibly delisted; no timezone found

No data found for JPS. Skipping...

$CPLG: possibly delisted; no timezone found

No data found for CPLG. Skipping...

$TCRD: possibly delisted; no timezone found

No data found for TCRD. Skipping...

$DS: possibly delisted; no timezone found

No data found for DS. Skipping...

$CPLP: possibly delisted; no timezone found
$YMAB: possibly delisted; no timezone found

No data found for CPLP. Skipping...
No data found for YMAB. Skipping...

$PFSW: possibly delisted; no timezone found

No data found for PFSW. Skipping...

$SCPE: possibly delisted; no timezone found
$ATUS: possibly delisted; no timezone found

No data found for SCPE. Skipping...
No data found for ATUS. Skipping...

$AMTBB: possibly delisted; no timezone found

No data found for AMTBB. Skipping...

$FL: possibly delisted; no timezone found

No data found for FL. Skipping...

$PAAC: possibly delisted; no timezone found

No data found for PAAC. Skipping...

$PCYG: possibly delisted; no timezone found

No data found for PCYG. Skipping...

$NLTX: possibly delisted; no timezone found
$THTX: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for NLTX. Skipping...
No data found for THTX. Skipping...

$HCCH: possibly delisted; no timezone found

No data found for HCCH. Skipping...

$MCC: possibly delisted; no timezone found

No data found for MCC. Skipping...

$CPTA: possibly delisted; no timezone found

No data found for CPTA. Skipping...

$ZIONN: possibly delisted; no timezone found

No data found for ZIONN. Skipping...

$ZOM: possibly delisted; no timezone found

No data found for ZOM. Skipping...

$SDC: possibly delisted; no timezone found

No data found for SDC. Skipping...

$JHB: possibly delisted; no timezone found

No data found for JHB. Skipping...

$CBH: possibly delisted; no timezone found

No data found for CBH. Skipping...

$PFIN: possibly delisted; no timezone found
$NWLI: possibly delisted; no timezone found

No data found for PFIN. Skipping...
No data found for NWLI. Skipping...

$LHCG: possibly delisted; no timezone found

No data found for LHCG. Skipping...

$MNE: possibly delisted; no timezone found

No data found for MNE. Skipping...

$TAST: possibly delisted; no timezone found

No data found for TAST. Skipping...

$TCBIL: possibly delisted; no timezone found

No data found for TCBIL. Skipping...

$ATNX: possibly delisted; no timezone found

No data found for ATNX. Skipping...

$ZNH: possibly delisted; no timezone found
$AXE: possibly delisted; no timezone found

No data found for ZNH. Skipping...
No data found for AXE. Skipping...

$ZIONO: possibly delisted; no timezone found

No data found for ZIONO. Skipping...

$TNP: possibly delisted; no timezone found

No data found for TNP. Skipping...

$ACAM: possibly delisted; no timezone found

No data found for ACAM. Skipping...

$SJI: possibly delisted; no timezone found

No data found for SJI. Skipping...

$HCCI: possibly delisted; no timezone found

No data found for HCCI. Skipping...

$QD: possibly delisted; no timezone found
$LMRK: possibly delisted; no timezone found

No data found for QD. Skipping...
No data found for LMRK. Skipping...

$NYMT: possibly delisted; no timezone found
$FSD: possibly delisted; no timezone found

No data found for NYMT. Skipping...

$LTRPB: possibly delisted; no timezone found

No data found for FSD. Skipping...
No data found for LTRPB. Skipping...

$THCBU: possibly delisted; no timezone found

No data found for THCBU. Skipping...

$PVBC: possibly delisted; no timezone found

No data found for PVBC. Skipping...

$HIE: possibly delisted; no timezone found
$AVLR: possibly delisted; no timezone found

No data found for HIE. Skipping...
No data found for AVLR. Skipping...

$TCRR: possibly delisted; no timezone found

No data found for TCRR. Skipping...

$PMBC: possibly delisted; no timezone found

No data found for PMBC. Skipping...

$CXP: possibly delisted; no timezone found

No data found for CXP. Skipping...

$MVC: possibly delisted; no timezone found

No data found for MVC. Skipping...

$PTMN: possibly delisted; no timezone found

No data found for PTMN. Skipping...

$ATVI: possibly delisted; no timezone found

No data found for ATVI. Skipping...

$FEI: possibly delisted; no timezone found

No data found for FEI. Skipping...

$GRIL: possibly delisted; no timezone found

No data found for GRIL. Skipping...

$QES: possibly delisted; no timezone found
$MGLN: possibly delisted; no timezone found

No data found for QES. Skipping...
No data found for MGLN. Skipping...

$MINI: possibly delisted; no timezone found

No data found for MINI. Skipping...

$ANH: possibly delisted; no timezone found

No data found for ANH. Skipping...

$QHC: possibly delisted; no timezone found

No data found for QHC. Skipping...

$CPAA: possibly delisted; no timezone found

No data found for CPAA. Skipping...

$EMKR: possibly delisted; no timezone found

No data found for EMKR. Skipping...

$MIME: possibly delisted; no timezone found

No data found for MIME. Skipping...

$VNE: possibly delisted; no timezone found
$GNUS: possibly delisted; no timezone found

No data found for VNE. Skipping...
No data found for GNUS. Skipping...

$MYL: possibly delisted; no timezone found
$GCI: possibly delisted; no timezone found

No data found for MYL. Skipping...
No data found for GCI. Skipping...

$SIEN: possibly delisted; no timezone found

No data found for SIEN. Skipping...

$OCCIP: possibly delisted; no timezone found

No data found for OCCIP. Skipping...

$MOBL: possibly delisted; no timezone found

No data found for MOBL. Skipping...

$RAVN: possibly delisted; no timezone found

No data found for RAVN. Skipping...

$ONEM: possibly delisted; no timezone found

No data found for ONEM. Skipping...

$SESN: possibly delisted; no timezone found

No data found for SESN. Skipping...

$YIN: possibly delisted; no timezone found

No data found for YIN. Skipping...

$CHEK: possibly delisted; no timezone found

No data found for CHEK. Skipping...

$FNJN: possibly delisted; no timezone found

No data found for FNJN. Skipping...

$BQH: possibly delisted; no timezone found

No data found for BQH. Skipping...

$USM: possibly delisted; no timezone found

No data found for USM. Skipping...

$NEW: possibly delisted; no timezone found

No data found for NEW. Skipping...

$KBAL: possibly delisted; no timezone found

No data found for KBAL. Skipping...

$PMX: possibly delisted; no timezone found

No data found for PMX. Skipping...

$TBNK: possibly delisted; no timezone found

No data found for TBNK. Skipping...

$NPA: possibly delisted; no timezone found

No data found for NPA. Skipping...

$WRTC: possibly delisted; no timezone found

No data found for WRTC. Skipping...

$BEST: possibly delisted; no timezone found

No data found for BEST. Skipping...

$PRVB: possibly delisted; no timezone found

No data found for PRVB. Skipping...

$BGIO: possibly delisted; no timezone found

No data found for BGIO. Skipping...

$EGIF: possibly delisted; no timezone found

No data found for EGIF. Skipping...

$WRK: possibly delisted; no timezone found

No data found for WRK. Skipping...

$ENLC: possibly delisted; no timezone found

No data found for ENLC. Skipping...

$TLND: possibly delisted; no timezone found

No data found for TLND. Skipping...

$ESGRO: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for ESGRO. Skipping...

$NVEE: possibly delisted; no timezone found

No data found for NVEE. Skipping...

$PVG: possibly delisted; no timezone found

No data found for PVG. Skipping...

$PAACU: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01) (Yahoo error = "Data doesn't exist for startDate = 1585800000, endDate = 1769922000")

No data found for PAACU. Skipping...

$WRI: possibly delisted; no timezone found

No data found for WRI. Skipping...

$MCBC: possibly delisted; no timezone found

No data found for MCBC. Skipping...

$HEAR: possibly delisted; no timezone found

No data found for HEAR. Skipping...

$CJJD: possibly delisted; no timezone found
$CFRX: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for CJJD. Skipping...
No data found for CFRX. Skipping...

$FIXX: possibly delisted; no timezone found

No data found for FIXX. Skipping...

$BGG: possibly delisted; no timezone found
$BRQS: possibly delisted; no timezone found

No data found for BGG. Skipping...
No data found for BRQS. Skipping...

$YNDX: possibly delisted; no timezone found

No data found for YNDX. Skipping...

$JCOM: possibly delisted; no timezone found

No data found for JCOM. Skipping...

$GXGXU: possibly delisted; no timezone found

No data found for GXGXU. Skipping...

$IHTA: possibly delisted; no timezone found

No data found for IHTA. Skipping...

$SWCH: possibly delisted; no timezone found

No data found for SWCH. Skipping...

$BPY: possibly delisted; no timezone found
$USX: possibly delisted; no timezone found

No data found for BPY. Skipping...
No data found for USX. Skipping...

$DOOR: possibly delisted; no timezone found

No data found for DOOR. Skipping...

$ICD: possibly delisted; no timezone found

No data found for ICD. Skipping...

$TYME: possibly delisted; no timezone found

No data found for TYME. Skipping...

$INT: possibly delisted; no timezone found

No data found for INT. Skipping...

$SPKE: possibly delisted; no timezone found

No data found for SPKE. Skipping...

$ONDK: possibly delisted; no timezone found
$RXN: possibly delisted; no timezone found

No data found for ONDK. Skipping...
No data found for RXN. Skipping...

$TWOU: possibly delisted; no timezone found

No data found for TWOU. Skipping...

$HOLI: possibly delisted; no timezone found

No data found for HOLI. Skipping...

$HES: possibly delisted; no timezone found

No data found for HES. Skipping...

$SSI: possibly delisted; no timezone found

No data found for SSI. Skipping...

$SPR: possibly delisted; no timezone found

No data found for SPR. Skipping...

$INWK: possibly delisted; no timezone found

No data found for INWK. Skipping...

$RIVE: possibly delisted; no timezone found
$CZZ: possibly delisted; no timezone found

No data found for RIVE. Skipping...
No data found for CZZ. Skipping...

$JRO: possibly delisted; no timezone found

No data found for JRO. Skipping...

$HHT: possibly delisted; no timezone found
$FFG: possibly delisted; no timezone found

No data found for HHT. Skipping...
No data found for FFG. Skipping...

$RENN: possibly delisted; no timezone found

No data found for RENN. Skipping...

$HHC: possibly delisted; no timezone found

No data found for HHC. Skipping...

$ONE: possibly delisted; no timezone found

No data found for ONE. Skipping...

$SKX: possibly delisted; no timezone found

No data found for SKX. Skipping...

$JEQ: possibly delisted; no timezone found

No data found for JEQ. Skipping...

$CMD: possibly delisted; no timezone found

No data found for CMD. Skipping...

$ESXB: possibly delisted; no timezone found

No data found for ESXB. Skipping...

$FCCY: possibly delisted; no timezone found

No data found for FCCY. Skipping...

$KMPH: possibly delisted; no timezone found

No data found for KMPH. Skipping...

$MNP: possibly delisted; no timezone found

No data found for MNP. Skipping...

$SFUN: possibly delisted; no timezone found

No data found for SFUN. Skipping...

$CCX: possibly delisted; no timezone found

No data found for CCX. Skipping...

$EXFO: possibly delisted; no timezone found

No data found for EXFO. Skipping...

$HPR: possibly delisted; no timezone found

No data found for HPR. Skipping...

$AAWW: possibly delisted; no timezone found

No data found for AAWW. Skipping...

$RGLS: possibly delisted; no timezone found

No data found for RGLS. Skipping...

$CIICU: possibly delisted; no timezone found

No data found for CIICU. Skipping...

$DFS: possibly delisted; no timezone found

No data found for DFS. Skipping...

$ACOR: possibly delisted; no timezone found

No data found for ACOR. Skipping...

$RETA: possibly delisted; no timezone found

No data found for RETA. Skipping...

$LAIX: possibly delisted; no timezone found

No data found for LAIX. Skipping...

$ZIONL: possibly delisted; no timezone found

No data found for ZIONL. Skipping...

$RNET: possibly delisted; no timezone found

No data found for RNET. Skipping...

$FMCIU: possibly delisted; no timezone found

No data found for FMCIU. Skipping...

$AAXN: possibly delisted; no timezone found

No data found for AAXN. Skipping...

$MCA: possibly delisted; no timezone found

No data found for MCA. Skipping...

$CNST: possibly delisted; no timezone found

No data found for CNST. Skipping...

$FRC: possibly delisted; no timezone found
$CECE: possibly delisted; no timezone found

No data found for FRC. Skipping...
No data found for CECE. Skipping...

$JFK: possibly delisted; no timezone found

No data found for JFK. Skipping...

$CSSEP: possibly delisted; no timezone found

No data found for CSSEP. Skipping...

$LTRPA: possibly delisted; no timezone found

No data found for LTRPA. Skipping...

$MCV: possibly delisted; no timezone found
$TCFC: possibly delisted; no timezone found

No data found for MCV. Skipping...
No data found for TCFC. Skipping...

$QEP: possibly delisted; no timezone found

No data found for QEP. Skipping...

$EDNT: possibly delisted; no timezone found

No data found for EDNT. Skipping...

$FFHL: possibly delisted; no timezone found

No data found for FFHL. Skipping...

$FGB: possibly delisted; no timezone found

No data found for FGB. Skipping...

$NUAN: possibly delisted; no timezone found

No data found for NUAN. Skipping...

$EXPC: possibly delisted; no timezone found

No data found for EXPC. Skipping...

$CTG: possibly delisted; no timezone found

No data found for CTG. Skipping...

$CNHI: possibly delisted; no timezone found

No data found for CNHI. Skipping...

$LIVKU: possibly delisted; no timezone found

No data found for LIVKU. Skipping...

$ETFC: possibly delisted; no timezone found

No data found for ETFC. Skipping...

$DSE: possibly delisted; no timezone found

No data found for DSE. Skipping...

$CNFRL: possibly delisted; no timezone found

No data found for CNFRL. Skipping...

$WDR: possibly delisted; no timezone found

No data found for WDR. Skipping...

$TESS: possibly delisted; no timezone found

No data found for TESS. Skipping...

$CSSE: possibly delisted; no timezone found

No data found for CSSE. Skipping...

$PBC: possibly delisted; no timezone found

No data found for PBC. Skipping...

$GSMG: possibly delisted; no timezone found

No data found for GSMG. Skipping...

$CHFS: possibly delisted; no timezone found

No data found for CHFS. Skipping...

$MANT: possibly delisted; no timezone found

No data found for MANT. Skipping...

$CTXS: possibly delisted; no timezone found

No data found for CTXS. Skipping...

$BRP: possibly delisted; no timezone found

No data found for BRP. Skipping...

$CCXI: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01) (Yahoo error = "Data doesn't exist for startDate = 1585800000, endDate = 1769922000")
$NTGN: possibly delisted; no timezone found

No data found for CCXI. Skipping...
No data found for NTGN. Skipping...

$IBA: possibly delisted; no timezone found

No data found for IBA. Skipping...

$PRAH: possibly delisted; no timezone found

No data found for PRAH. Skipping...

$BREW: possibly delisted; no timezone found

No data found for BREW. Skipping...

$NDP: possibly delisted; no timezone found

No data found for NDP. Skipping...

$BRG: possibly delisted; no timezone found

No data found for BRG. Skipping...

$SWAV: possibly delisted; no timezone found

No data found for SWAV. Skipping...

$SBNA: possibly delisted; no timezone found
$BRPA: possibly delisted; no timezone found

No data found for SBNA. Skipping...
No data found for BRPA. Skipping...

$GXGX: possibly delisted; no timezone found

No data found for GXGX. Skipping...

$DISCK: possibly delisted; no timezone found

No data found for DISCK. Skipping...

$TRHC: possibly delisted; no timezone found

No data found for TRHC. Skipping...

$ICPT: possibly delisted; no timezone found

No data found for ICPT. Skipping...

$ACGLP: possibly delisted; no timezone found

No data found for ACGLP. Skipping...

$CHRA: possibly delisted; no timezone found
$PING: possibly delisted; no timezone found

No data found for CHRA. Skipping...
No data found for PING. Skipping...

$GTT: possibly delisted; no timezone found

No data found for GTT. Skipping...

$ROLL: possibly delisted; no timezone found

No data found for ROLL. Skipping...

$ENX: possibly delisted; no timezone found

No data found for ENX. Skipping...

$FLIC: possibly delisted; no timezone found

No data found for FLIC. Skipping...

$SBBX: possibly delisted; no timezone found

No data found for SBBX. Skipping...

$OYST: possibly delisted; no timezone found

No data found for OYST. Skipping...

$ELJ: possibly delisted; no timezone found

No data found for ELJ. Skipping...

$GWB: possibly delisted; no timezone found

No data found for GWB. Skipping...

$WRE: possibly delisted; no timezone found

No data found for WRE. Skipping...

$PRVL: possibly delisted; no timezone found

No data found for PRVL. Skipping...

$BFO: possibly delisted; no timezone found

No data found for BFO. Skipping...

$MTOR: possibly delisted; no timezone found

No data found for MTOR. Skipping...

$NXGN: possibly delisted; no timezone found

No data found for NXGN. Skipping...

$KLR: possibly delisted; no timezone found

No data found for KLR. Skipping...

$OPTN: possibly delisted; no timezone found

No data found for OPTN. Skipping...

$PNM: possibly delisted; no timezone found

No data found for PNM. Skipping...

$RVI: possibly delisted; no timezone found
$SYNL: possibly delisted; no timezone found

No data found for RVI. Skipping...
No data found for SYNL. Skipping...

$FPAC: possibly delisted; no timezone found

No data found for FPAC. Skipping...

$MFGP: possibly delisted; no timezone found

No data found for MFGP. Skipping...

$GBT: possibly delisted; no timezone found

No data found for GBT. Skipping...

$GMDA: possibly delisted; no timezone found

No data found for GMDA. Skipping...

$GCP: possibly delisted; no timezone found

No data found for GCP. Skipping...

$COWNL: possibly delisted; no timezone found

No data found for COWNL. Skipping...

$NJV: possibly delisted; no timezone found

No data found for NJV. Skipping...

$CVLY: possibly delisted; no timezone found

No data found for CVLY. Skipping...

$TTP: possibly delisted; no timezone found

No data found for TTP. Skipping...

$SHLO: possibly delisted; no timezone found

No data found for SHLO. Skipping...

$GNTY: possibly delisted; no timezone found
$SPI: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for GNTY. Skipping...
No data found for SPI. Skipping...

$DNJR: possibly delisted; no timezone found

No data found for DNJR. Skipping...

$SHLX: possibly delisted; no timezone found

No data found for SHLX. Skipping...

$PTAC: possibly delisted; no timezone found

No data found for PTAC. Skipping...

$BXRX: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for BXRX. Skipping...

$HMTV: possibly delisted; no timezone found

No data found for HMTV. Skipping...

$OCN: possibly delisted; no timezone found

No data found for OCN. Skipping...

$PFPT: possibly delisted; no timezone found

No data found for PFPT. Skipping...

$CETV: possibly delisted; no timezone found

No data found for CETV. Skipping...

$ADSW: possibly delisted; no timezone found

No data found for ADSW. Skipping...

$CBPO: possibly delisted; no timezone found

No data found for CBPO. Skipping...

$ATTO: possibly delisted; no timezone found
$EARS: possibly delisted; no timezone found

No data found for ATTO. Skipping...
No data found for EARS. Skipping...

$EVRI: possibly delisted; no timezone found

No data found for EVRI. Skipping...

$BASI: possibly delisted; no timezone found

No data found for BASI. Skipping...

$ATH: possibly delisted; no timezone found

No data found for ATH. Skipping...

$DRAD: possibly delisted; no timezone found

No data found for DRAD. Skipping...

$SAQNU: possibly delisted; no timezone found

No data found for SAQNU. Skipping...

$BHLB: possibly delisted; no timezone found

No data found for BHLB. Skipping...

$PACD: possibly delisted; no timezone found

No data found for PACD. Skipping...

$HMLP: possibly delisted; no timezone found

No data found for HMLP. Skipping...

$CELP: possibly delisted; no timezone found

No data found for CELP. Skipping...

$FMBI: possibly delisted; no timezone found

No data found for FMBI. Skipping...

$MMP: possibly delisted; no timezone found

No data found for MMP. Skipping...

$CLDR: possibly delisted; no timezone found

No data found for CLDR. Skipping...

$MNK: possibly delisted; no timezone found

No data found for MNK. Skipping...

$SMED: possibly delisted; no timezone found

No data found for SMED. Skipping...

$TSLF: possibly delisted; no timezone found
$AYX: possibly delisted; no timezone found

No data found for TSLF. Skipping...

$TMDI: possibly delisted; no timezone found

No data found for AYX. Skipping...
No data found for TMDI. Skipping...

$MRLN: possibly delisted; no timezone found

No data found for MRLN. Skipping...

$JIH: possibly delisted; no timezone found
$MBII: possibly delisted; no timezone found

No data found for JIH. Skipping...
No data found for MBII. Skipping...

$ZIONW: possibly delisted; no timezone found

No data found for ZIONW. Skipping...

$SASR: possibly delisted; no timezone found
$SFE: possibly delisted; no timezone found

No data found for SASR. Skipping...
No data found for SFE. Skipping...

$PFHD: possibly delisted; no timezone found

No data found for PFHD. Skipping...

$TBK: possibly delisted; no timezone found

No data found for TBK. Skipping...

$CAJ: possibly delisted; no timezone found

No data found for CAJ. Skipping...

$TCO: possibly delisted; no timezone found

No data found for TCO. Skipping...

$HTBX: possibly delisted; no timezone found

No data found for HTBX. Skipping...

$SC: possibly delisted; no timezone found

No data found for SC. Skipping...

$FCBP: possibly delisted; no timezone found

No data found for FCBP. Skipping...

$ATAX: possibly delisted; no timezone found

No data found for ATAX. Skipping...

$AMNB: possibly delisted; no timezone found

No data found for AMNB. Skipping...

$RP: possibly delisted; no timezone found

No data found for RP. Skipping...

$QK: possibly delisted; no timezone found

No data found for QK. Skipping...

$REXN: possibly delisted; no timezone found

No data found for REXN. Skipping...

$FSRV: possibly delisted; no timezone found
$AAMC: possibly delisted; no timezone found

No data found for FSRV. Skipping...
No data found for AAMC. Skipping...

$VBTX: possibly delisted; no timezone found

No data found for VBTX. Skipping...

$VAR: possibly delisted; no timezone found

No data found for VAR. Skipping...

$ACTT: possibly delisted; no timezone found

No data found for ACTT. Skipping...

$AOBC: possibly delisted; no timezone found
$SOGO: possibly delisted; no timezone found

No data found for AOBC. Skipping...
No data found for SOGO. Skipping...

$GLOP: possibly delisted; no timezone found

No data found for GLOP. Skipping...

$NLOK: possibly delisted; no timezone found

No data found for NLOK. Skipping...

$MYT: possibly delisted; no timezone found

No data found for MYT. Skipping...

$GLOG: possibly delisted; no timezone found

No data found for GLOG. Skipping...

$CUO: possibly delisted; no timezone found

No data found for CUO. Skipping...

$AMK: possibly delisted; no timezone found
$OCX: possibly delisted; no timezone found

No data found for AMK. Skipping...
No data found for OCX. Skipping...

$DLPH: possibly delisted; no timezone found

No data found for DLPH. Skipping...

$CTK: possibly delisted; no timezone found

No data found for CTK. Skipping...

$MYC: possibly delisted; no timezone found

No data found for MYC. Skipping...

$ALO: possibly delisted; no timezone found

No data found for ALO. Skipping...

$SQBG: possibly delisted; no timezone found
$CALB: possibly delisted; no timezone found

No data found for SQBG. Skipping...
No data found for CALB. Skipping...

$TWNK: possibly delisted; no timezone found

No data found for TWNK. Skipping...

$PCK: possibly delisted; no timezone found

No data found for PCK. Skipping...

$FRTA: possibly delisted; no timezone found
$CSPR: possibly delisted; no timezone found

No data found for FRTA. Skipping...
No data found for CSPR. Skipping...

$COWNZ: possibly delisted; no timezone found

No data found for COWNZ. Skipping...

$DFFN: possibly delisted; no timezone found

No data found for DFFN. Skipping...

$GMZ: possibly delisted; no timezone found

No data found for GMZ. Skipping...

$SGEN: possibly delisted; no timezone found

No data found for SGEN. Skipping...

$CONE: possibly delisted; no timezone found

No data found for CONE. Skipping...

$YRCW: possibly delisted; no timezone found

No data found for YRCW. Skipping...

$ETM: possibly delisted; no timezone found

No data found for ETM. Skipping...

$IAA: possibly delisted; no timezone found

No data found for IAA. Skipping...

$NEX: possibly delisted; no timezone found
$BPT: possibly delisted; no timezone found

No data found for NEX. Skipping...
No data found for BPT. Skipping...

$SUNW: possibly delisted; no timezone found

No data found for SUNW. Skipping...

$KNL: possibly delisted; no timezone found
$IVH: possibly delisted; no timezone found

No data found for KNL. Skipping...
No data found for IVH. Skipping...

$NPN: possibly delisted; no timezone found

No data found for NPN. Skipping...

$BFY: possibly delisted; no timezone found
$FBHS: possibly delisted; no timezone found

No data found for BFY. Skipping...
No data found for FBHS. Skipping...

$RBZ: possibly delisted; no timezone found

No data found for RBZ. Skipping...

$CVTI: possibly delisted; no timezone found

No data found for CVTI. Skipping...

$GPAQU: possibly delisted; no timezone found

No data found for GPAQU. Skipping...

$CATS: possibly delisted; no timezone found
$TWTR: possibly delisted; no timezone found

No data found for CATS. Skipping...
No data found for TWTR. Skipping...

$GSUM: possibly delisted; no timezone found

No data found for GSUM. Skipping...

$MDGS: possibly delisted; no timezone found
$ALJJ: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for MDGS. Skipping...
No data found for ALJJ. Skipping...

$SEEL: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)
$BLUE: possibly delisted; no timezone found

No data found for SEEL. Skipping...
No data found for BLUE. Skipping...

$SREV: possibly delisted; no timezone found

No data found for SREV. Skipping...

$EMX: possibly delisted; no timezone found

No data found for EMX. Skipping...

$MTBC: possibly delisted; no timezone found

No data found for MTBC. Skipping...

$BKI: possibly delisted; no timezone found

No data found for BKI. Skipping...

$GVP: possibly delisted; no timezone found
$ENT: possibly delisted; no timezone found

No data found for GVP. Skipping...
No data found for ENT. Skipping...

$ENOB: possibly delisted; no timezone found
$HCCOU: possibly delisted; no timezone found

No data found for ENOB. Skipping...

$GECCN: possibly delisted; no timezone found

No data found for HCCOU. Skipping...
No data found for GECCN. Skipping...

$ENV: possibly delisted; no timezone found

No data found for ENV. Skipping...

$BKK: possibly delisted; no timezone found

No data found for BKK. Skipping...

$LFC: possibly delisted; no timezone found

No data found for LFC. Skipping...

$IPLDP: possibly delisted; no timezone found

No data found for IPLDP. Skipping...

$BPYUP: possibly delisted; no timezone found
$ORAN: possibly delisted; no timezone found

No data found for BPYUP. Skipping...
No data found for ORAN. Skipping...

$AKCA: possibly delisted; no timezone found

No data found for AKCA. Skipping...

$GFLU: possibly delisted; no timezone found

No data found for GFLU. Skipping...

$GOGL: possibly delisted; no timezone found

No data found for GOGL. Skipping...

$NSTG: possibly delisted; no timezone found
$PEAK: possibly delisted; no timezone found

No data found for NSTG. Skipping...
No data found for PEAK. Skipping...

$ISBC: possibly delisted; no timezone found

No data found for ISBC. Skipping...

$KIRK: possibly delisted; no timezone found

No data found for KIRK. Skipping...

$GMO: possibly delisted; no timezone found

No data found for GMO. Skipping...

$ALRN: possibly delisted; no timezone found

No data found for ALRN. Skipping...

$GNC: possibly delisted; no timezone found

No data found for GNC. Skipping...

$ORTX: possibly delisted; no timezone found

No data found for ORTX. Skipping...

$ANDA: possibly delisted; no timezone found

No data found for ANDA. Skipping...

$ROYT: possibly delisted; no timezone found

No data found for ROYT. Skipping...

$OPNT: possibly delisted; no timezone found

No data found for OPNT. Skipping...

$THBRU: possibly delisted; no timezone found

No data found for THBRU. Skipping...

$AXNX: possibly delisted; no timezone found

No data found for AXNX. Skipping...

$IO: possibly delisted; no timezone found

No data found for IO. Skipping...

$JT: possibly delisted; no timezone found

No data found for JT. Skipping...

$SHLL: possibly delisted; no timezone found

No data found for SHLL. Skipping...

$TMST: possibly delisted; no timezone found

No data found for TMST. Skipping...

$CVA: possibly delisted; no timezone found

No data found for CVA. Skipping...

$HHHH: possibly delisted; no timezone found
$BHTG: possibly delisted; no timezone found

No data found for HHHH. Skipping...
No data found for BHTG. Skipping...

$MFINL: possibly delisted; no timezone found

No data found for MFINL. Skipping...

$JSD: possibly delisted; no timezone found

No data found for JSD. Skipping...

$MICT: possibly delisted; no timezone found
$EAST: possibly delisted; no timezone found

No data found for MICT. Skipping...
No data found for EAST. Skipping...

$ZUO: possibly delisted; no timezone found

No data found for ZUO. Skipping...

$UROV: possibly delisted; no timezone found

No data found for UROV. Skipping...

$CRTX: possibly delisted; no timezone found
$ALGRU: possibly delisted; no timezone found

No data found for CRTX. Skipping...
No data found for ALGRU. Skipping...

$SORL: possibly delisted; no timezone found

No data found for SORL. Skipping...

$MAG: possibly delisted; no timezone found

No data found for MAG. Skipping...

$MNRL: possibly delisted; no timezone found

No data found for MNRL. Skipping...

$RE: possibly delisted; no timezone found

No data found for RE. Skipping...

$AMBC: possibly delisted; no timezone found

No data found for AMBC. Skipping...

$JHY: possibly delisted; no timezone found

No data found for JHY. Skipping...

$CBD: possibly delisted; no timezone found

No data found for CBD. Skipping...

$MRNS: possibly delisted; no timezone found

No data found for MRNS. Skipping...

$HTLF: possibly delisted; no timezone found
$QUOT: possibly delisted; no timezone found

No data found for HTLF. Skipping...
No data found for QUOT. Skipping...

$SCHN: possibly delisted; no timezone found

No data found for SCHN. Skipping...

$HJLIW: possibly delisted; no timezone found
$SGB: possibly delisted; no timezone found

No data found for HJLIW. Skipping...
No data found for SGB. Skipping...

$SAQN: possibly delisted; no timezone found

No data found for SAQN. Skipping...

$NEPT: possibly delisted; no timezone found

No data found for NEPT. Skipping...

$HRC: possibly delisted; no timezone found

No data found for HRC. Skipping...

$THCAU: possibly delisted; no timezone found
$LMST: possibly delisted; no timezone found

No data found for THCAU. Skipping...
No data found for LMST. Skipping...

$CNSL: possibly delisted; no timezone found

No data found for CNSL. Skipping...

$PVAC: possibly delisted; no timezone found

No data found for PVAC. Skipping...

$TLC: possibly delisted; no timezone found

No data found for TLC. Skipping...

$AUY: possibly delisted; no timezone found

No data found for AUY. Skipping...

$MUDSU: possibly delisted; no timezone found

No data found for MUDSU. Skipping...

$SJR: possibly delisted; no timezone found

No data found for SJR. Skipping...

$PACQ: possibly delisted; no timezone found

No data found for PACQ. Skipping...

$FDEF: possibly delisted; no timezone found

No data found for FDEF. Skipping...

$NYMX: possibly delisted; no timezone found

No data found for NYMX. Skipping...

$OMP: possibly delisted; no timezone found

No data found for OMP. Skipping...

$ACC: possibly delisted; no timezone found

No data found for ACC. Skipping...

$SCPH: possibly delisted; no timezone found
$JPI: possibly delisted; no timezone found

No data found for SCPH. Skipping...
No data found for JPI. Skipping...

$STRM: possibly delisted; no timezone found

No data found for STRM. Skipping...

$MWK: possibly delisted; no timezone found

No data found for MWK. Skipping...

$MTP: possibly delisted; no timezone found

No data found for MTP. Skipping...

$AFIN: possibly delisted; no timezone found

No data found for AFIN. Skipping...

$CLSN: possibly delisted; no timezone found

No data found for CLSN. Skipping...

$OAS: possibly delisted; no timezone found

No data found for OAS. Skipping...

$FIF: possibly delisted; no timezone found

No data found for FIF. Skipping...

$SRC: possibly delisted; no timezone found

No data found for SRC. Skipping...

$SRT: possibly delisted; no timezone found

No data found for SRT. Skipping...

$OBSV: possibly delisted; no timezone found

No data found for OBSV. Skipping...

$IMV: possibly delisted; no timezone found

No data found for IMV. Skipping...

$BRKS: possibly delisted; no timezone found

No data found for BRKS. Skipping...

$PBIP: possibly delisted; no timezone found

No data found for PBIP. Skipping...

$PGTI: possibly delisted; no timezone found

No data found for PGTI. Skipping...

$NKG: possibly delisted; no timezone found

No data found for NKG. Skipping...

$OPOF: possibly delisted; no timezone found

No data found for OPOF. Skipping...

$MACK: possibly delisted; no timezone found

No data found for MACK. Skipping...

$ALSK: possibly delisted; no timezone found

No data found for ALSK. Skipping...

$NSCO: possibly delisted; no timezone found
$LBAI: possibly delisted; no timezone found

No data found for NSCO. Skipping...
No data found for LBAI. Skipping...

$PICO: possibly delisted; no timezone found
$VCIF: possibly delisted; no timezone found

No data found for PICO. Skipping...
No data found for VCIF. Skipping...

$SWTX: possibly delisted; no timezone found

No data found for SWTX. Skipping...

$CCMP: possibly delisted; no timezone found

No data found for CCMP. Skipping...

$BDR: possibly delisted; no timezone found

No data found for BDR. Skipping...

$DSKE: possibly delisted; no timezone found

No data found for DSKE. Skipping...

$RTTR: possibly delisted; no timezone found

No data found for RTTR. Skipping...

$ELVT: possibly delisted; no timezone found

No data found for ELVT. Skipping...

$WPX: possibly delisted; no timezone found

No data found for WPX. Skipping...

$PNNTG: possibly delisted; no timezone found

No data found for PNNTG. Skipping...

$ORBC: possibly delisted; no timezone found

No data found for ORBC. Skipping...

$CCCL: possibly delisted; no timezone found

No data found for CCCL. Skipping...

$TEDU: possibly delisted; no timezone found

No data found for TEDU. Skipping...

$PPBI: possibly delisted; no timezone found
$PTE: possibly delisted; no timezone found

No data found for PPBI. Skipping...
No data found for PTE. Skipping...

$MSGN: possibly delisted; no timezone found

No data found for MSGN. Skipping...

$FRBK: possibly delisted; no timezone found

No data found for FRBK. Skipping...

$BIF: possibly delisted; no timezone found

No data found for BIF. Skipping...

$TWNKW: possibly delisted; no timezone found
$ESGRP: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for TWNKW. Skipping...
No data found for ESGRP. Skipping...

$WSG: possibly delisted; no timezone found
$MAXR: possibly delisted; no timezone found

No data found for WSG. Skipping...
No data found for MAXR. Skipping...

$PTR: possibly delisted; no timezone found

No data found for PTR. Skipping...

$NHLD: possibly delisted; no timezone found

No data found for NHLD. Skipping...

$ORCC: possibly delisted; no timezone found

No data found for ORCC. Skipping...

$HEBT: possibly delisted; no timezone found

No data found for HEBT. Skipping...

$ARNA: possibly delisted; no timezone found

No data found for ARNA. Skipping...

$ECT: possibly delisted; no timezone found
$VSLR: possibly delisted; no timezone found

No data found for ECT. Skipping...
No data found for VSLR. Skipping...

$CCLP: possibly delisted; no timezone found
$UFS: possibly delisted; no timezone found

No data found for CCLP. Skipping...
No data found for UFS. Skipping...

$WETF: possibly delisted; no timezone found

No data found for WETF. Skipping...

$PZN: possibly delisted; no timezone found

No data found for PZN. Skipping...

$WEBK: possibly delisted; no timezone found

No data found for WEBK. Skipping...

$BEDU: possibly delisted; no timezone found

No data found for BEDU. Skipping...

$IMVTU: possibly delisted; no timezone found

No data found for IMVTU. Skipping...

$AINV: possibly delisted; no timezone found

No data found for AINV. Skipping...

$DOOO: possibly delisted; no timezone found

No data found for DOOO. Skipping...

$TNAV: possibly delisted; no timezone found

No data found for TNAV. Skipping...

$HUSA: possibly delisted; no timezone found

No data found for HUSA. Skipping...

$PRMW: possibly delisted; no timezone found

No data found for PRMW. Skipping...

$APOP: possibly delisted; no timezone found

No data found for APOP. Skipping...

$IMGN: possibly delisted; no timezone found

No data found for IMGN. Skipping...

$CFFAU: possibly delisted; no timezone found

No data found for CFFAU. Skipping...

$SAEX: possibly delisted; no timezone found

No data found for SAEX. Skipping...

$CTL: possibly delisted; no timezone found

No data found for CTL. Skipping...

$MTT: possibly delisted; no timezone found

No data found for MTT. Skipping...

$ABC: possibly delisted; no timezone found
$VIACA: possibly delisted; no timezone found

No data found for ABC. Skipping...
No data found for VIACA. Skipping...

$NBLX: possibly delisted; no timezone found
$HJV: possibly delisted; no timezone found

No data found for NBLX. Skipping...
No data found for HJV. Skipping...

$SCPL: possibly delisted; no timezone found

No data found for SCPL. Skipping...

$DRTT: possibly delisted; no timezone found

No data found for DRTT. Skipping...

$VERY: possibly delisted; no timezone found

No data found for VERY. Skipping...

$CNBKA: possibly delisted; no timezone found

No data found for CNBKA. Skipping...

$MRTX: possibly delisted; no timezone found

No data found for MRTX. Skipping...

$CXO: possibly delisted; no timezone found

No data found for CXO. Skipping...

$TTPH: possibly delisted; no timezone found

No data found for TTPH. Skipping...

$FDEU: possibly delisted; no timezone found
$VNTR: possibly delisted; no timezone found

No data found for FDEU. Skipping...
No data found for VNTR. Skipping...

$MUDS: possibly delisted; no timezone found

No data found for MUDS. Skipping...

$AMOV: possibly delisted; no timezone found

No data found for AMOV. Skipping...

$SHI: possibly delisted; no timezone found

No data found for SHI. Skipping...

$INNT: possibly delisted; no timezone found

No data found for INNT. Skipping...

$MLHR: possibly delisted; no timezone found

No data found for MLHR. Skipping...

$TOTAU: possibly delisted; no timezone found

No data found for TOTAU. Skipping...

$ACBI: possibly delisted; no timezone found

No data found for ACBI. Skipping...

$MITO: possibly delisted; no timezone found

No data found for MITO. Skipping...

$HSKA: possibly delisted; no timezone found

No data found for HSKA. Skipping...

$SFTW: possibly delisted; no timezone found

No data found for SFTW. Skipping...

$NGHC: possibly delisted; no timezone found

No data found for NGHC. Skipping...

$TARO: possibly delisted; no timezone found

No data found for TARO. Skipping...

$PCTI: possibly delisted; no timezone found
$GNCA: possibly delisted; no timezone found

No data found for PCTI. Skipping...
No data found for GNCA. Skipping...

$HYACU: possibly delisted; no timezone found
$CCR: possibly delisted; no timezone found

No data found for HYACU. Skipping...
No data found for CCR. Skipping...

$AFINP: possibly delisted; no timezone found
$CLGX: possibly delisted; no timezone found

No data found for AFINP. Skipping...
No data found for CLGX. Skipping...

$HSC: possibly delisted; no timezone found
$HSII: possibly delisted; no timezone found

No data found for HSC. Skipping...
No data found for HSII. Skipping...

$CLDB: possibly delisted; no timezone found

No data found for CLDB. Skipping...

$MGTA: possibly delisted; no timezone found
$BSTC: possibly delisted; no timezone found

No data found for MGTA. Skipping...
No data found for BSTC. Skipping...

$DDF: possibly delisted; no timezone found

No data found for DDF. Skipping...

$SJW: possibly delisted; no timezone found

No data found for SJW. Skipping...

$ACTTU: possibly delisted; no timezone found

No data found for ACTTU. Skipping...

$CMO: possibly delisted; no timezone found
$HTBI: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for CMO. Skipping...
No data found for HTBI. Skipping...

$TCDA: possibly delisted; no timezone found
$COG: possibly delisted; no timezone found

No data found for TCDA. Skipping...
No data found for COG. Skipping...

$GNMK: possibly delisted; no timezone found

No data found for GNMK. Skipping...

$NBACU: possibly delisted; no timezone found

No data found for NBACU. Skipping...

$FTCH: possibly delisted; no timezone found

No data found for FTCH. Skipping...

$ECHO: possibly delisted; no timezone found

No data found for ECHO. Skipping...

$DL: possibly delisted; no timezone found
$AAN: possibly delisted; no timezone found

No data found for DL. Skipping...
No data found for AAN. Skipping...

$XOG: possibly delisted; no timezone found
$RUHN: possibly delisted; no timezone found

No data found for XOG. Skipping...
No data found for RUHN. Skipping...

$CBSHP: possibly delisted; no timezone found

No data found for CBSHP. Skipping...

$ABB: possibly delisted; no timezone found

No data found for ABB. Skipping...

$HIL: possibly delisted; no timezone found
$AXAS: possibly delisted; no timezone found

No data found for HIL. Skipping...
No data found for AXAS. Skipping...

$FIT: possibly delisted; no timezone found

No data found for FIT. Skipping...

$VMW: possibly delisted; no timezone found

No data found for VMW. Skipping...

$JP: possibly delisted; no timezone found
$CUI: possibly delisted; no timezone found

No data found for JP. Skipping...
No data found for CUI. Skipping...

$HFC: possibly delisted; no timezone found

No data found for HFC. Skipping...

$SPN: possibly delisted; no timezone found

No data found for SPN. Skipping...

$CPAH: possibly delisted; no timezone found

No data found for CPAH. Skipping...

$CINR: possibly delisted; no timezone found
$SRF: possibly delisted; no timezone found

No data found for CINR. Skipping...
No data found for SRF. Skipping...

$HX: possibly delisted; no timezone found

No data found for HX. Skipping...

$PAE: possibly delisted; no timezone found

No data found for PAE. Skipping...

$HNGR: possibly delisted; no timezone found

No data found for HNGR. Skipping...

$ISNS: possibly delisted; no timezone found
$SNCA: possibly delisted; no timezone found

No data found for ISNS. Skipping...
No data found for SNCA. Skipping...

$TRPX: possibly delisted; no timezone found
$LATNU: possibly delisted; no timezone found

No data found for TRPX. Skipping...
No data found for LATNU. Skipping...

$RDFN: possibly delisted; no timezone found

No data found for RDFN. Skipping...

$PMF: possibly delisted; no timezone found

No data found for PMF. Skipping...

$COOP: possibly delisted; no timezone found
$UCBI: possibly delisted; no timezone found

No data found for COOP. Skipping...
No data found for UCBI. Skipping...

$CFFA: possibly delisted; no timezone found

No data found for CFFA. Skipping...

$ABIO: possibly delisted; no timezone found

No data found for ABIO. Skipping...

$ENBA: possibly delisted; no timezone found
$BERY: possibly delisted; no timezone found

No data found for ENBA. Skipping...
No data found for BERY. Skipping...

$KMF: possibly delisted; no timezone found
$SLCT: possibly delisted; no timezone found

No data found for KMF. Skipping...
No data found for SLCT. Skipping...

$DISCA: possibly delisted; no timezone found

No data found for DISCA. Skipping...

$TPRE: possibly delisted; no timezone found
$CATB: possibly delisted; no timezone found

No data found for TPRE. Skipping...
No data found for CATB. Skipping...

$NSS: possibly delisted; no timezone found
$WINS: possibly delisted; no timezone found

No data found for NSS. Skipping...
No data found for WINS. Skipping...

$LGC: possibly delisted; no timezone found

No data found for LGC. Skipping...

$HUGE: possibly delisted; no timezone found

No data found for HUGE. Skipping...

$BIG: possibly delisted; no timezone found
$ENG: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for BIG. Skipping...
No data found for ENG. Skipping...

$PUB: possibly delisted; no timezone found

No data found for PUB. Skipping...

$ARCE: possibly delisted; no timezone found

No data found for ARCE. Skipping...

$JMLP: possibly delisted; no timezone found

No data found for JMLP. Skipping...

$CSFL: possibly delisted; no timezone found

No data found for CSFL. Skipping...

$EBTC: possibly delisted; no timezone found

No data found for EBTC. Skipping...

$EIGI: possibly delisted; no timezone found

No data found for EIGI. Skipping...

$AGTC: possibly delisted; no timezone found
$AIZP: possibly delisted; no timezone found

No data found for AGTC. Skipping...
No data found for AIZP. Skipping...

$PBPB: possibly delisted; no timezone found
$SLCA: possibly delisted; no timezone found

No data found for PBPB. Skipping...
No data found for SLCA. Skipping...

$OXSQZ: possibly delisted; no timezone found

No data found for OXSQZ. Skipping...

$RCM: possibly delisted; no timezone found

No data found for RCM. Skipping...

$PBFX: possibly delisted; no timezone found
$PMD: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for PBFX. Skipping...
No data found for PMD. Skipping...

$BRFS: possibly delisted; no timezone found

No data found for BRFS. Skipping...

$EVA: possibly delisted; no timezone found

No data found for EVA. Skipping...

$ZYNE: possibly delisted; no timezone found

No data found for ZYNE. Skipping...

$FTACU: possibly delisted; no timezone found

No data found for FTACU. Skipping...

$POL: possibly delisted; no timezone found

No data found for POL. Skipping...

$AGLE: possibly delisted; no timezone found

No data found for AGLE. Skipping...

$TWMC: possibly delisted; no timezone found

No data found for TWMC. Skipping...

$GARS: possibly delisted; no timezone found
$WEI: possibly delisted; no timezone found

No data found for GARS. Skipping...
No data found for WEI. Skipping...

$XAN: possibly delisted; no timezone found

No data found for XAN. Skipping...

$JE: possibly delisted; no timezone found

No data found for JE. Skipping...

$TMSR: possibly delisted; no timezone found

No data found for TMSR. Skipping...

$OAC: possibly delisted; no timezone found
$FIV: possibly delisted; no timezone found

No data found for OAC. Skipping...
No data found for FIV. Skipping...

$AXLA: possibly delisted; no timezone found

No data found for AXLA. Skipping...

$HHHHU: possibly delisted; no timezone found
$MUS: possibly delisted; no timezone found

No data found for HHHHU. Skipping...
No data found for MUS. Skipping...

$PTLA: possibly delisted; no timezone found

No data found for PTLA. Skipping...

$CURO: possibly delisted; no timezone found

No data found for CURO. Skipping...

$HZNP: possibly delisted; no timezone found
$MAV: possibly delisted; no timezone found

No data found for HZNP. Skipping...
No data found for MAV. Skipping...

$GBLIZ: possibly delisted; no timezone found

No data found for GBLIZ. Skipping...

$XLNX: possibly delisted; no timezone found

No data found for XLNX. Skipping...

$CLI: possibly delisted; no timezone found
$SP: possibly delisted; no timezone found

No data found for CLI. Skipping...
No data found for SP. Skipping...

$TORC: possibly delisted; no timezone found

No data found for TORC. Skipping...

$HAYN: possibly delisted; no timezone found
$ASFI: possibly delisted; no timezone found

No data found for HAYN. Skipping...
No data found for ASFI. Skipping...

$CCF: possibly delisted; no timezone found

No data found for CCF. Skipping...

$CBB: possibly delisted; no timezone found
$ESSCU: possibly delisted; no timezone found

No data found for CBB. Skipping...
No data found for ESSCU. Skipping...

$TCBIP: possibly delisted; no timezone found

No data found for TCBIP. Skipping...

$LGF.B: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)
$TAT: possibly delisted; no timezone found

No data found for LGF.B. Skipping...
No data found for TAT. Skipping...

$ETRN: possibly delisted; no timezone found
$SDI: possibly delisted; no timezone found

No data found for ETRN. Skipping...
No data found for SDI. Skipping...

$ANDAU: possibly delisted; no timezone found

No data found for ANDAU. Skipping...

$MTBCP: possibly delisted; no timezone found

No data found for MTBCP. Skipping...

$NYCB: possibly delisted; no timezone found

No data found for NYCB. Skipping...

$AXO: possibly delisted; no timezone found

No data found for AXO. Skipping...

$FMCI: possibly delisted; no timezone found

No data found for FMCI. Skipping...

$PFIE: possibly delisted; no timezone found

No data found for PFIE. Skipping...

$RPLA: possibly delisted; no timezone found

No data found for RPLA. Skipping...

$SSNT: possibly delisted; no timezone found

No data found for SSNT. Skipping...

$PACW: possibly delisted; no timezone found
$VVI: possibly delisted; no timezone found

No data found for PACW. Skipping...
No data found for VVI. Skipping...

$SQ: possibly delisted; no timezone found

No data found for SQ. Skipping...

$FTAC: possibly delisted; no timezone found

No data found for FTAC. Skipping...

$SIX: possibly delisted; no timezone found

No data found for SIX. Skipping...

$AMOT: possibly delisted; no timezone found

No data found for AMOT. Skipping...

$VTA: possibly delisted; no timezone found

No data found for VTA. Skipping...

$PATI: possibly delisted; no timezone found
$LTHM: possibly delisted; no timezone found

No data found for PATI. Skipping...
No data found for LTHM. Skipping...

$DO: possibly delisted; no timezone found

No data found for DO. Skipping...

$EVSI: possibly delisted; no timezone found

No data found for EVSI. Skipping...

$FSRVU: possibly delisted; no timezone found

No data found for FSRVU. Skipping...

$GRIF: possibly delisted; no timezone found

No data found for GRIF. Skipping...

$DPW: possibly delisted; no timezone found

No data found for DPW. Skipping...

$TUP: possibly delisted; no timezone found

No data found for TUP. Skipping...

$MYF: possibly delisted; no timezone found

No data found for MYF. Skipping...

$HOME: possibly delisted; no timezone found
$SAGE: possibly delisted; no timezone found

No data found for HOME. Skipping...
No data found for SAGE. Skipping...

$CTY: possibly delisted; no timezone found

No data found for CTY. Skipping...

$RTLR: possibly delisted; no timezone found

No data found for RTLR. Skipping...

$BLCM: possibly delisted; no timezone found
$SIVBP: possibly delisted; no timezone found

No data found for BLCM. Skipping...
No data found for SIVBP. Skipping...

$RMBL: possibly delisted; no timezone found

No data found for RMBL. Skipping...

$LPI: possibly delisted; no timezone found

No data found for LPI. Skipping...

$RYB: possibly delisted; no timezone found

No data found for RYB. Skipping...

$KTP: possibly delisted; no timezone found

No data found for KTP. Skipping...

$HEXO: possibly delisted; no timezone found

No data found for HEXO. Skipping...

$AINC: possibly delisted; no timezone found
$SYNH: possibly delisted; no timezone found

No data found for AINC. Skipping...
No data found for SYNH. Skipping...

$BRY: possibly delisted; no timezone found

No data found for BRY. Skipping...

$PLIN: possibly delisted; no timezone found

No data found for PLIN. Skipping...

$PME: possibly delisted; no timezone found

No data found for PME. Skipping...

$MFSF: possibly delisted; no timezone found

No data found for MFSF. Skipping...

$DISCB: possibly delisted; no timezone found

No data found for DISCB. Skipping...

$EBR: possibly delisted; no timezone found

No data found for EBR. Skipping...

$APTO: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for APTO. Skipping...

$FLDM: possibly delisted; no timezone found

No data found for FLDM. Skipping...

$ARNC: possibly delisted; no timezone found
$OXSQL: possibly delisted; no timezone found

No data found for ARNC. Skipping...
No data found for OXSQL. Skipping...

$PXD: possibly delisted; no timezone found

No data found for PXD. Skipping...

$RAD: possibly delisted; no timezone found

No data found for RAD. Skipping...

$APTX: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for APTX. Skipping...

$ANPC: possibly delisted; no timezone found

No data found for ANPC. Skipping...

$LDL: possibly delisted; no timezone found

No data found for LDL. Skipping...

$ELY: possibly delisted; no timezone found

No data found for ELY. Skipping...

$RMG: possibly delisted; no timezone found

No data found for RMG. Skipping...

$GHIV: possibly delisted; no timezone found

No data found for GHIV. Skipping...

$SIVB: possibly delisted; no timezone found
$UMRX: possibly delisted; no timezone found

No data found for SIVB. Skipping...
No data found for UMRX. Skipping...

$MDLA: possibly delisted; no timezone found

No data found for MDLA. Skipping...

$NEBUW: possibly delisted; no timezone found

No data found for NEBUW. Skipping...

$RFP: possibly delisted; no timezone found

No data found for RFP. Skipping...

$CTIC: possibly delisted; no timezone found

No data found for CTIC. Skipping...

$BPMP: possibly delisted; no timezone found

No data found for BPMP. Skipping...

$PRSC: possibly delisted; no timezone found

No data found for PRSC. Skipping...

$ICAD: possibly delisted; no timezone found

No data found for ICAD. Skipping...

$BPYU: possibly delisted; no timezone found
$IGT: possibly delisted; no timezone found

No data found for BPYU. Skipping...
No data found for IGT. Skipping...

$EQC: possibly delisted; no timezone found
$OPES: possibly delisted; no timezone found

No data found for EQC. Skipping...
No data found for OPES. Skipping...

$TANNZ: possibly delisted; no timezone found

No data found for TANNZ. Skipping...

$MDRRP: possibly delisted; no timezone found

No data found for MDRRP. Skipping...

$WBK: possibly delisted; no timezone found

No data found for WBK. Skipping...

$EROS: possibly delisted; no timezone found

No data found for EROS. Skipping...

$LLEX: possibly delisted; no timezone found

No data found for LLEX. Skipping...

$MSVB: possibly delisted; no timezone found

No data found for MSVB. Skipping...

$PEI: possibly delisted; no timezone found

No data found for PEI. Skipping...

$LUB: possibly delisted; no timezone found

No data found for LUB. Skipping...

$EBIX: possibly delisted; no timezone found

No data found for EBIX. Skipping...

$LIZI: possibly delisted; no timezone found

No data found for LIZI. Skipping...

$CVIA: possibly delisted; no timezone found

No data found for CVIA. Skipping...

$ZNGA: possibly delisted; no timezone found
$NK: possibly delisted; no timezone found

No data found for ZNGA. Skipping...
No data found for NK. Skipping...

$UNVR: possibly delisted; no timezone found

No data found for UNVR. Skipping...

$MYOK: possibly delisted; no timezone found

No data found for MYOK. Skipping...

$SWN: possibly delisted; no timezone found

No data found for SWN. Skipping...

$REDU: possibly delisted; no timezone found

No data found for REDU. Skipping...

$IRBT: possibly delisted; no timezone found

No data found for IRBT. Skipping...

$IRCP: possibly delisted; no timezone found

No data found for IRCP. Skipping...

$MLVF: possibly delisted; no timezone found

No data found for MLVF. Skipping...

$SAMA: possibly delisted; no timezone found

No data found for SAMA. Skipping...

$FTSV: possibly delisted; no timezone found

No data found for FTSV. Skipping...

$AVID: possibly delisted; no timezone found

No data found for AVID. Skipping...

$I: possibly delisted; no timezone found

No data found for I. Skipping...

$CIT: possibly delisted; no timezone found
$SJIU: possibly delisted; no timezone found

No data found for CIT. Skipping...
No data found for SJIU. Skipping...

$GMHIU: possibly delisted; no timezone found

No data found for GMHIU. Skipping...

$EVBG: possibly delisted; no timezone found

No data found for EVBG. Skipping...

$BMTC: possibly delisted; no timezone found

No data found for BMTC. Skipping...

$MGP: possibly delisted; no timezone found
$RILYO: possibly delisted; no timezone found

No data found for MGP. Skipping...
No data found for RILYO. Skipping...

$MFT: possibly delisted; no timezone found

No data found for MFT. Skipping...

$FVE: possibly delisted; no timezone found

No data found for FVE. Skipping...

$NYMTN: possibly delisted; no timezone found

No data found for NYMTN. Skipping...

$NWHM: possibly delisted; no timezone found
$OTIC: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for NWHM. Skipping...
No data found for OTIC. Skipping...

$ZN: possibly delisted; no timezone found

No data found for ZN. Skipping...

$MKD: possibly delisted; no timezone found

No data found for MKD. Skipping...

$BOCH: possibly delisted; no timezone found

No data found for BOCH. Skipping...

$HAPP: possibly delisted; no timezone found

No data found for HAPP. Skipping...

$MKGI: possibly delisted; no timezone found

No data found for MKGI. Skipping...

$CPSI: possibly delisted; no timezone found

No data found for CPSI. Skipping...

$DCF: possibly delisted; no timezone found

No data found for DCF. Skipping...

$HCHC: possibly delisted; no timezone found

No data found for HCHC. Skipping...

$ATIF: possibly delisted; no timezone found

No data found for ATIF. Skipping...

$WTRH: possibly delisted; no timezone found

No data found for WTRH. Skipping...

$CLCT: possibly delisted; no timezone found
$CBMG: possibly delisted; no timezone found

No data found for CLCT. Skipping...
No data found for CBMG. Skipping...

$MHI: possibly delisted; no timezone found

No data found for MHI. Skipping...

$CEA: possibly delisted; no timezone found

No data found for CEA. Skipping...

$CDR: possibly delisted; no timezone found

No data found for CDR. Skipping...

$AVRO: possibly delisted; no timezone found

No data found for AVRO. Skipping...

$DCP: possibly delisted; no timezone found

No data found for DCP. Skipping...

$ADMS: possibly delisted; no timezone found

No data found for ADMS. Skipping...

$UNAM: possibly delisted; no timezone found
$MEN: possibly delisted; no timezone found

No data found for UNAM. Skipping...
No data found for MEN. Skipping...

$NYMTO: possibly delisted; no timezone found

No data found for NYMTO. Skipping...

$VIVO: possibly delisted; no timezone found
$FORD: possibly delisted; no timezone found

No data found for VIVO. Skipping...
No data found for FORD. Skipping...

$SOI: possibly delisted; no timezone found

No data found for SOI. Skipping...

$ADAP: possibly delisted; no timezone found

No data found for ADAP. Skipping...

$AE: possibly delisted; no timezone found
$CERC: possibly delisted; no timezone found

No data found for AE. Skipping...
No data found for CERC. Skipping...

$FAM: possibly delisted; no timezone found
$JTA: possibly delisted; no timezone found

No data found for FAM. Skipping...
No data found for JTA. Skipping...

$CYAD: possibly delisted; no timezone found

No data found for CYAD. Skipping...

$BVXV: possibly delisted; no timezone found

No data found for BVXV. Skipping...

$SMTX: possibly delisted; no timezone found
$SUP: possibly delisted; no timezone found

No data found for SMTX. Skipping...
No data found for SUP. Skipping...

$AIW: possibly delisted; no timezone found

No data found for AIW. Skipping...

$RTIX: possibly delisted; no timezone found

No data found for RTIX. Skipping...

$SBPH: possibly delisted; no timezone found

No data found for SBPH. Skipping...

$SWIR: possibly delisted; no timezone found

No data found for SWIR. Skipping...

$GER: possibly delisted; no timezone found

No data found for GER. Skipping...

$SGLB: possibly delisted; no timezone found
$KRA: possibly delisted; no timezone found

No data found for SGLB. Skipping...
No data found for KRA. Skipping...

$LIVK: possibly delisted; no timezone found

No data found for LIVK. Skipping...

$CSWCL: possibly delisted; no timezone found
$TCFCP: possibly delisted; no timezone found

No data found for CSWCL. Skipping...
No data found for TCFCP. Skipping...

$AIKI: possibly delisted; no timezone found

No data found for AIKI. Skipping...

$PHX: possibly delisted; no timezone found

No data found for PHX. Skipping...

$USAK: possibly delisted; no timezone found

No data found for USAK. Skipping...

$CVET: possibly delisted; no timezone found

No data found for CVET. Skipping...

$TANNL: possibly delisted; no timezone found

No data found for TANNL. Skipping...

$PRFT: possibly delisted; no timezone found

No data found for PRFT. Skipping...

$CTIB: possibly delisted; no timezone found

No data found for CTIB. Skipping...

$CSOD: possibly delisted; no timezone found

No data found for CSOD. Skipping...

$NTUS: possibly delisted; no timezone found

No data found for NTUS. Skipping...

$ANTM: possibly delisted; no timezone found

No data found for ANTM. Skipping...

$OBAS: possibly delisted; no timezone found

No data found for OBAS. Skipping...

$NXQ: possibly delisted; no timezone found
$SECO: possibly delisted; no timezone found

No data found for NXQ. Skipping...
No data found for SECO. Skipping...

$UMPQ: possibly delisted; no timezone found
$BIOL: possibly delisted; no timezone found

No data found for UMPQ. Skipping...
No data found for BIOL. Skipping...

$MSBF: possibly delisted; no timezone found
$ALNA: possibly delisted; no timezone found

No data found for MSBF. Skipping...
No data found for ALNA. Skipping...

$GPS: possibly delisted; no timezone found

No data found for GPS. Skipping...

$GSH: possibly delisted; no timezone found

No data found for GSH. Skipping...

$ENIA: possibly delisted; no timezone found
$LINX: possibly delisted; no timezone found

No data found for ENIA. Skipping...
No data found for LINX. Skipping...

$BLL: possibly delisted; no timezone found

No data found for BLL. Skipping...

$GMLPP: possibly delisted; no timezone found

No data found for GMLPP. Skipping...

$MINDP: possibly delisted; no timezone found

No data found for MINDP. Skipping...

$BLPH: possibly delisted; no timezone found

No data found for BLPH. Skipping...

$ALLK: possibly delisted; no timezone found
$EPAY: possibly delisted; no timezone found

No data found for ALLK. Skipping...
No data found for EPAY. Skipping...

$TECD: possibly delisted; no timezone found
$BGNE: possibly delisted; no timezone found

No data found for TECD. Skipping...
No data found for BGNE. Skipping...

$SELB: possibly delisted; no timezone found

No data found for SELB. Skipping...

$NTG: possibly delisted; no timezone found

No data found for NTG. Skipping...

$USWS: possibly delisted; no timezone found

No data found for USWS. Skipping...

$ISR: possibly delisted; no timezone found
$EBSB: possibly delisted; no timezone found

No data found for ISR. Skipping...
No data found for EBSB. Skipping...

$NTP: possibly delisted; no timezone found
$CASA: possibly delisted; no timezone found

No data found for NTP. Skipping...
No data found for CASA. Skipping...

$TKAT: possibly delisted; no timezone found

No data found for TKAT. Skipping...

$TLRD: possibly delisted; no timezone found

No data found for TLRD. Skipping...

$DMPI: possibly delisted; no timezone found

No data found for DMPI. Skipping...

$ITCB: possibly delisted; no timezone found

No data found for ITCB. Skipping...

$ICBK: possibly delisted; no timezone found
$PIRS: possibly delisted; no timezone found

No data found for ICBK. Skipping...
No data found for PIRS. Skipping...

$ALTM: possibly delisted; no timezone found

No data found for ALTM. Skipping...

$LMRKO: possibly delisted; no timezone found
$TRXC: possibly delisted; no timezone found

No data found for LMRKO. Skipping...
No data found for TRXC. Skipping...

$SPNE: possibly delisted; no timezone found
$DRADP: possibly delisted; no timezone found

No data found for SPNE. Skipping...
No data found for DRADP. Skipping...

$NVUS: possibly delisted; no timezone found

No data found for NVUS. Skipping...

$ISIG: possibly delisted; no timezone found

No data found for ISIG. Skipping...

$GGO: possibly delisted; no timezone found
$AUTO: possibly delisted; no timezone found

No data found for GGO. Skipping...
No data found for AUTO. Skipping...

$ONCT: possibly delisted; no timezone found

No data found for ONCT. Skipping...

$GNRSU: possibly delisted; no timezone found

No data found for GNRSU. Skipping...

$JHAA: possibly delisted; no timezone found

No data found for JHAA. Skipping...

$SGMS: possibly delisted; no timezone found

No data found for SGMS. Skipping...

$ALXN: possibly delisted; no timezone found

No data found for ALXN. Skipping...

$NMCI: possibly delisted; no timezone found

No data found for NMCI. Skipping...

$CWBR: possibly delisted; no timezone found
$XEC: possibly delisted; no timezone found

No data found for CWBR. Skipping...
No data found for XEC. Skipping...

$WORK: possibly delisted; no timezone found

No data found for WORK. Skipping...

$SWM: possibly delisted; no timezone found

No data found for SWM. Skipping...

$NH: possibly delisted; no timezone found

No data found for NH. Skipping...

$TPX: possibly delisted; no timezone found
$TSC: possibly delisted; no timezone found

No data found for TPX. Skipping...
No data found for TSC. Skipping...

$SONA: possibly delisted; no timezone found

No data found for SONA. Skipping...

$RNWK: possibly delisted; no timezone found
$DVD: possibly delisted; no timezone found

No data found for RNWK. Skipping...
No data found for DVD. Skipping...

$CO: possibly delisted; no timezone found

No data found for CO. Skipping...

$ECOL: possibly delisted; no timezone found
$THGA: possibly delisted; no timezone found

No data found for ECOL. Skipping...
No data found for THGA. Skipping...

$AXDX: possibly delisted; no timezone found

No data found for AXDX. Skipping...

$HLG: possibly delisted; no timezone found

No data found for HLG. Skipping...

$LAWS: possibly delisted; no timezone found

No data found for LAWS. Skipping...

$FBC: possibly delisted; no timezone found

No data found for FBC. Skipping...

$AXGT: possibly delisted; no timezone found

No data found for AXGT. Skipping...

$AFMD: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for AFMD. Skipping...

$AMHC: possibly delisted; no timezone found
$PSXP: possibly delisted; no timezone found

No data found for AMHC. Skipping...
No data found for PSXP. Skipping...

$CHS: possibly delisted; no timezone found

No data found for CHS. Skipping...

$CKH: possibly delisted; no timezone found

No data found for CKH. Skipping...

$QTT: possibly delisted; no timezone found
$STAY: possibly delisted; no timezone found

No data found for QTT. Skipping...
No data found for STAY. Skipping...

$NYMTM: possibly delisted; no timezone found

No data found for NYMTM. Skipping...

$MNTX: possibly delisted; no timezone found

No data found for MNTX. Skipping...

$CREE: possibly delisted; no timezone found
$HBANO: possibly delisted; no timezone found

No data found for CREE. Skipping...
No data found for HBANO. Skipping...

$JBN: possibly delisted; no timezone found
$HTA: possibly delisted; no timezone found

No data found for JBN. Skipping...
No data found for HTA. Skipping...

$TDJ: possibly delisted; no timezone found

No data found for TDJ. Skipping...

$NEWR: possibly delisted; no timezone found

No data found for NEWR. Skipping...

$INFN: possibly delisted; no timezone found
$AMED: possibly delisted; no timezone found

No data found for INFN. Skipping...
No data found for AMED. Skipping...

$STOR: possibly delisted; no timezone found

No data found for STOR. Skipping...

$XENT: possibly delisted; no timezone found

No data found for XENT. Skipping...

$CFX: possibly delisted; no timezone found

No data found for CFX. Skipping...

$CLBS: possibly delisted; no timezone found

No data found for CLBS. Skipping...

$WTREP: possibly delisted; no timezone found

No data found for WTREP. Skipping...

$STML: possibly delisted; no timezone found

No data found for STML. Skipping...

$PHAS: possibly delisted; no timezone found

No data found for PHAS. Skipping...

$ADMP: possibly delisted; no timezone found

No data found for ADMP. Skipping...

$OSB: possibly delisted; no timezone found
$HUD: possibly delisted; no timezone found

No data found for OSB. Skipping...
No data found for HUD. Skipping...

$HSON: possibly delisted; no timezone found

No data found for HSON. Skipping...

$ASLN: possibly delisted; no timezone found

No data found for ASLN. Skipping...

$TGP: possibly delisted; no timezone found

No data found for TGP. Skipping...

$HBANN: possibly delisted; no timezone found
$OCFT: possibly delisted; no timezone found

No data found for HBANN. Skipping...
No data found for OCFT. Skipping...

$MFV: possibly delisted; no timezone found

No data found for MFV. Skipping...

$VRS: possibly delisted; no timezone found

No data found for VRS. Skipping...

$FFNW: possibly delisted; no timezone found

No data found for FFNW. Skipping...

$EBAYL: possibly delisted; no timezone found

No data found for EBAYL. Skipping...

$CY: possibly delisted; no timezone found
$K: possibly delisted; no timezone found

No data found for CY. Skipping...
No data found for K. Skipping...

$JWN: possibly delisted; no timezone found

No data found for JWN. Skipping...

$MESA: possibly delisted; no timezone found

No data found for MESA. Skipping...

$BMCH: possibly delisted; no timezone found

No data found for BMCH. Skipping...

$ADVM: possibly delisted; no timezone found

No data found for ADVM. Skipping...

$VGR: possibly delisted; no timezone found
$ADS: possibly delisted; no timezone found

No data found for VGR. Skipping...
No data found for ADS. Skipping...

$SCWX: possibly delisted; no timezone found
$ECOM: possibly delisted; no timezone found

No data found for SCWX. Skipping...
No data found for ECOM. Skipping...

$WMGI: possibly delisted; no timezone found
$FOE: possibly delisted; no timezone found

No data found for WMGI. Skipping...
No data found for FOE. Skipping...

$AJX: possibly delisted; no timezone found

No data found for AJX. Skipping...

$AIC: possibly delisted; no timezone found

No data found for AIC. Skipping...

$MGEN: possibly delisted; no timezone found

No data found for MGEN. Skipping...

$TRQ: possibly delisted; no timezone found

No data found for TRQ. Skipping...

$MR: possibly delisted; no timezone found

No data found for MR. Skipping...

$OFC: possibly delisted; no timezone found

No data found for OFC. Skipping...

$TSU: possibly delisted; no timezone found

No data found for TSU. Skipping...

$NVTA: possibly delisted; no timezone found

No data found for NVTA. Skipping...

$SPNS: possibly delisted; no timezone found

No data found for SPNS. Skipping...

$LMRKN: possibly delisted; no timezone found

No data found for LMRKN. Skipping...

$SMMCU: possibly delisted; no timezone found

No data found for SMMCU. Skipping...

$CDXC: possibly delisted; no timezone found

No data found for CDXC. Skipping...

$ISEE: possibly delisted; no timezone found

No data found for ISEE. Skipping...

$PIH: possibly delisted; no timezone found

No data found for PIH. Skipping...

$BBF: possibly delisted; no timezone found

No data found for BBF. Skipping...

$ENDP: possibly delisted; no timezone found

No data found for ENDP. Skipping...

$EYEN: possibly delisted; no timezone found
$TRNX: possibly delisted; no timezone found

No data found for EYEN. Skipping...
No data found for TRNX. Skipping...

$JMPNZ: possibly delisted; no timezone found

No data found for JMPNZ. Skipping...

$BBQ: possibly delisted; no timezone found

No data found for BBQ. Skipping...

$VVUS: possibly delisted; no timezone found

No data found for VVUS. Skipping...

$KBSF: possibly delisted; no timezone found
$IDRA: possibly delisted; no timezone found

No data found for KBSF. Skipping...
No data found for IDRA. Skipping...

$TRMT: possibly delisted; no timezone found

No data found for TRMT. Skipping...

$NEBUU: possibly delisted; no timezone found

No data found for NEBUU. Skipping...

$WIFI: possibly delisted; no timezone found
$NXR: possibly delisted; no timezone found

No data found for WIFI. Skipping...
No data found for NXR. Skipping...

$CFXA: possibly delisted; no timezone found

No data found for CFXA. Skipping...

$NYV: possibly delisted; no timezone found

No data found for NYV. Skipping...

$SEAS: possibly delisted; no timezone found
$GTYH: possibly delisted; no timezone found

No data found for SEAS. Skipping...
No data found for GTYH. Skipping...

$IBKCP: possibly delisted; no timezone found

No data found for IBKCP. Skipping...

$TRCH: possibly delisted; no timezone found

No data found for TRCH. Skipping...

$GPP: possibly delisted; no timezone found

No data found for GPP. Skipping...

$EHT: possibly delisted; no timezone found

No data found for EHT. Skipping...

$PSB: possibly delisted; no timezone found
$ONTX: possibly delisted; no timezone found

No data found for PSB. Skipping...
No data found for ONTX. Skipping...

$BGCP: possibly delisted; no timezone found

No data found for BGCP. Skipping...

$ZEAL: possibly delisted; no timezone found

No data found for ZEAL. Skipping...

$MOSY: possibly delisted; no timezone found
$PTACU: possibly delisted; no timezone found

No data found for MOSY. Skipping...
No data found for PTACU. Skipping...

$LCI: possibly delisted; no timezone found

No data found for LCI. Skipping...

$HEES: possibly delisted; no timezone found

No data found for HEES. Skipping...

$LSXMA: possibly delisted; no timezone found

No data found for LSXMA. Skipping...

$SPTN: possibly delisted; no timezone found
$UBX: possibly delisted; no timezone found

No data found for SPTN. Skipping...
No data found for UBX. Skipping...

$EFL: possibly delisted; no timezone found

No data found for EFL. Skipping...

$EURN: possibly delisted; no timezone found

No data found for EURN. Skipping...

$APRN: possibly delisted; no timezone found
$GHSI: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for APRN. Skipping...
No data found for GHSI. Skipping...

$RRD: possibly delisted; no timezone found

No data found for RRD. Skipping...

$BITA: possibly delisted; no timezone found
$ISDR: possibly delisted; no timezone found

No data found for BITA. Skipping...
No data found for ISDR. Skipping...

$NBO: possibly delisted; no timezone found

No data found for NBO. Skipping...

$SYKE: possibly delisted; no timezone found

No data found for SYKE. Skipping...

$CHNG: possibly delisted; no timezone found
$ERI: possibly delisted; no timezone found

No data found for CHNG. Skipping...
No data found for ERI. Skipping...

$MXIM: possibly delisted; no timezone found

No data found for MXIM. Skipping...

$GCAP: possibly delisted; no timezone found
$PBCT: possibly delisted; no timezone found

No data found for GCAP. Skipping...
No data found for PBCT. Skipping...

$KSU: possibly delisted; no timezone found
$GFY: possibly delisted; no timezone found

No data found for KSU. Skipping...
No data found for GFY. Skipping...

$BKEPP: possibly delisted; no timezone found

No data found for BKEPP. Skipping...

$AESE: possibly delisted; no timezone found
$NLS: possibly delisted; no timezone found

No data found for AESE. Skipping...
No data found for NLS. Skipping...

$IIN: possibly delisted; no timezone found
$LKCO: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for IIN. Skipping...
No data found for LKCO. Skipping...

$GFN: possibly delisted; no timezone found
$SGMA: possibly delisted; no timezone found

No data found for GFN. Skipping...
No data found for SGMA. Skipping...

$CFMS: possibly delisted; no timezone found

No data found for CFMS. Skipping...

$PDCE: possibly delisted; no timezone found

No data found for PDCE. Skipping...

$ZFGN: possibly delisted; no timezone found

No data found for ZFGN. Skipping...

$AHC: possibly delisted; no timezone found
$CPG: possibly delisted; no timezone found

No data found for AHC. Skipping...
No data found for CPG. Skipping...

$HBI: possibly delisted; no timezone found

No data found for HBI. Skipping...

$CKPT: possibly delisted; no timezone found
$AMRH: possibly delisted; no timezone found

No data found for CKPT. Skipping...
No data found for AMRH. Skipping...

$AMCIU: possibly delisted; no timezone found

No data found for AMCIU. Skipping...

$CIIC: possibly delisted; no timezone found

No data found for CIIC. Skipping...

$NM: possibly delisted; no timezone found

No data found for NM. Skipping...

$CPTAL: possibly delisted; no timezone found

No data found for CPTAL. Skipping...

$AZRE: possibly delisted; no timezone found

No data found for AZRE. Skipping...

$SALT: possibly delisted; no timezone found

No data found for SALT. Skipping...

$SDPI: possibly delisted; no timezone found

No data found for SDPI. Skipping...

$KTOV: possibly delisted; no timezone found

No data found for KTOV. Skipping...

$X: possibly delisted; no timezone found

No data found for X. Skipping...

$AFH: possibly delisted; no timezone found

No data found for AFH. Skipping...

$SCVX: possibly delisted; no timezone found

No data found for SCVX. Skipping...

$ACST: possibly delisted; no timezone found

No data found for ACST. Skipping...

$JCO: possibly delisted; no timezone found
$PIHPP: possibly delisted; no timezone found

No data found for JCO. Skipping...
No data found for PIHPP. Skipping...

$UIHC: possibly delisted; no timezone found

No data found for UIHC. Skipping...

$GWGH: possibly delisted; no timezone found

No data found for GWGH. Skipping...

$FWP: possibly delisted; no timezone found

No data found for FWP. Skipping...

$CIR: possibly delisted; no timezone found

No data found for CIR. Skipping...

$CLNC: possibly delisted; no timezone found
$LANC: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for CLNC. Skipping...
No data found for LANC. Skipping...

$JRJC: possibly delisted; no timezone found

No data found for JRJC. Skipping...

$TGC: possibly delisted; no timezone found

No data found for TGC. Skipping...

$ROSEU: possibly delisted; no timezone found

No data found for ROSEU. Skipping...

$VBIV: possibly delisted; no timezone found

No data found for VBIV. Skipping...

$STND: possibly delisted; no timezone found

No data found for STND. Skipping...

$LOAC: possibly delisted; no timezone found

No data found for LOAC. Skipping...

$EVOP: possibly delisted; no timezone found
$MBINO: possibly delisted; no timezone found

No data found for EVOP. Skipping...
No data found for MBINO. Skipping...

$IGMS: possibly delisted; no timezone found

No data found for IGMS. Skipping...

$CEIX: possibly delisted; no timezone found

No data found for CEIX. Skipping...

$BDSI: possibly delisted; no timezone found

No data found for BDSI. Skipping...

$NEWA: possibly delisted; no timezone found

No data found for NEWA. Skipping...

$CNXM: possibly delisted; no timezone found

No data found for CNXM. Skipping...

$MIK: possibly delisted; no timezone found

No data found for MIK. Skipping...

$ETTX: possibly delisted; no timezone found

No data found for ETTX. Skipping...

$HYB: possibly delisted; no timezone found
$CPAAU: possibly delisted; no timezone found

No data found for HYB. Skipping...
No data found for CPAAU. Skipping...

$MFD: possibly delisted; no timezone found

No data found for MFD. Skipping...

$HZN: possibly delisted; no timezone found

No data found for HZN. Skipping...

$RILYH: possibly delisted; no timezone found

No data found for RILYH. Skipping...

$VRTV: possibly delisted; no timezone found
$AFI: possibly delisted; no timezone found

No data found for VRTV. Skipping...
No data found for AFI. Skipping...

$VTIQU: possibly delisted; no timezone found

No data found for VTIQU. Skipping...

$AT: possibly delisted; no timezone found

No data found for AT. Skipping...

$HMG: possibly delisted; no timezone found

No data found for HMG. Skipping...

$OXLCM: possibly delisted; no timezone found
$Y: possibly delisted; no timezone found

No data found for OXLCM. Skipping...
No data found for Y. Skipping...

$AC: possibly delisted; no timezone found

No data found for AC. Skipping...

$AQNA: possibly delisted; no timezone found

No data found for AQNA. Skipping...

$SVMK: possibly delisted; no timezone found

No data found for SVMK. Skipping...

$BCOV: possibly delisted; no timezone found

No data found for BCOV. Skipping...

$SWI: possibly delisted; no timezone found

No data found for SWI. Skipping...

$REGI: possibly delisted; no timezone found
$CLVS: possibly delisted; no timezone found

No data found for REGI. Skipping...
No data found for CLVS. Skipping...

$AIF: possibly delisted; no timezone found

No data found for AIF. Skipping...

$CRY: possibly delisted; no timezone found

No data found for CRY. Skipping...

$RUBY: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)
$TSG: possibly delisted; no timezone found

No data found for RUBY. Skipping...
No data found for TSG. Skipping...

$NATI: possibly delisted; no timezone found

No data found for NATI. Skipping...

$NEWTL: possibly delisted; no timezone found
$TRWH: possibly delisted; no timezone found

No data found for NEWTL. Skipping...
No data found for TRWH. Skipping...

$GDP: possibly delisted; no timezone found

No data found for GDP. Skipping...

$TEUM: possibly delisted; no timezone found

No data found for TEUM. Skipping...

$GSKY: possibly delisted; no timezone found

No data found for GSKY. Skipping...

$GEC: possibly delisted; no timezone found

No data found for GEC. Skipping...

$SRACU: possibly delisted; no timezone found

No data found for SRACU. Skipping...

$WTFCM: possibly delisted; no timezone found
$APHA: possibly delisted; no timezone found

No data found for WTFCM. Skipping...
No data found for APHA. Skipping...

$CCRC: possibly delisted; no timezone found

No data found for CCRC. Skipping...

$NTCO: possibly delisted; no timezone found

No data found for NTCO. Skipping...

$TPCO: possibly delisted; no timezone found

No data found for TPCO. Skipping...

$MFAC: possibly delisted; no timezone found

No data found for MFAC. Skipping...

$SILK: possibly delisted; no timezone found

No data found for SILK. Skipping...

$BTN: possibly delisted; no timezone found

No data found for BTN. Skipping...

$AKRX: possibly delisted; no timezone found

No data found for AKRX. Skipping...

$WMC: possibly delisted; no timezone found
$NOVN: possibly delisted; no timezone found

No data found for WMC. Skipping...
No data found for NOVN. Skipping...

$USCR: possibly delisted; no timezone found

No data found for USCR. Skipping...

$AKRO: possibly delisted; no timezone found

No data found for AKRO. Skipping...

$BNFT: possibly delisted; no timezone found

No data found for BNFT. Skipping...

$IRR: possibly delisted; no timezone found

No data found for IRR. Skipping...

$PLXP: possibly delisted; no timezone found

No data found for PLXP. Skipping...

$CARA: possibly delisted; no timezone found
$JMEI: possibly delisted; no timezone found

No data found for CARA. Skipping...
No data found for JMEI. Skipping...

$ABMD: possibly delisted; no timezone found

No data found for ABMD. Skipping...

$UFAB: possibly delisted; no timezone found

No data found for UFAB. Skipping...

$IHIT: possibly delisted; no timezone found

No data found for IHIT. Skipping...

$RADA: possibly delisted; no timezone found
$PPX: possibly delisted; no timezone found

No data found for RADA. Skipping...
No data found for PPX. Skipping...

$IFFT: possibly delisted; no timezone found

No data found for IFFT. Skipping...

$CDMOP: possibly delisted; no timezone found

No data found for CDMOP. Skipping...

$PSV: possibly delisted; no timezone found

No data found for PSV. Skipping...

$CHUY: possibly delisted; no timezone found

No data found for CHUY. Skipping...

$LBY: possibly delisted; no timezone found
$WTT: possibly delisted; no timezone found

No data found for LBY. Skipping...
No data found for WTT. Skipping...

$TLGT: possibly delisted; no timezone found

No data found for TLGT. Skipping...

$LSXMB: possibly delisted; no timezone found

No data found for LSXMB. Skipping...

$PLYA: possibly delisted; no timezone found

No data found for PLYA. Skipping...

$NAOV: possibly delisted; no timezone found

No data found for NAOV. Skipping...

$HGSH: possibly delisted; no timezone found

No data found for HGSH. Skipping...

$OBLG: possibly delisted; no timezone found

No data found for OBLG. Skipping...

$TYHT: possibly delisted; no timezone found
$ARYAU: possibly delisted; no timezone found

No data found for TYHT. Skipping...
No data found for ARYAU. Skipping...

$SINA: possibly delisted; no timezone found
$NBL: possibly delisted; no timezone found

No data found for SINA. Skipping...
No data found for NBL. Skipping...

$RST: possibly delisted; no timezone found

No data found for RST. Skipping...

$IDEX: possibly delisted; no timezone found

No data found for IDEX. Skipping...

$LIVX: possibly delisted; no timezone found

No data found for LIVX. Skipping...

$ERJ: possibly delisted; no timezone found

No data found for ERJ. Skipping...

$ROSE: possibly delisted; no timezone found

No data found for ROSE. Skipping...

$NCBS: possibly delisted; no timezone found

No data found for NCBS. Skipping...

$ORSN: possibly delisted; no timezone found

No data found for ORSN. Skipping...

$SPLK: possibly delisted; no timezone found

No data found for SPLK. Skipping...

$AMRK: possibly delisted; no timezone found

No data found for AMRK. Skipping...

$HMST: possibly delisted; no timezone found

No data found for HMST. Skipping...

$AZPN: possibly delisted; no timezone found
$SONG: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for AZPN. Skipping...
No data found for SONG. Skipping...

$SOLO: possibly delisted; no timezone found
$CNNB: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for SOLO. Skipping...
No data found for CNNB. Skipping...

$NRBO: possibly delisted; no timezone found
$MNLO: possibly delisted; no timezone found

No data found for NRBO. Skipping...
No data found for MNLO. Skipping...

$NEBU: possibly delisted; no timezone found

No data found for NEBU. Skipping...

$INSI: possibly delisted; no timezone found

No data found for INSI. Skipping...

$CGIX: possibly delisted; no timezone found

No data found for CGIX. Skipping...

$EMAN: possibly delisted; no timezone found
$OXFD: possibly delisted; no timezone found

No data found for EMAN. Skipping...
No data found for OXFD. Skipping...

$EMCF: possibly delisted; no timezone found

No data found for EMCF. Skipping...

$MSG: possibly delisted; no timezone found
$VTIQW: possibly delisted; no timezone found

No data found for MSG. Skipping...
No data found for VTIQW. Skipping...

$LATN: possibly delisted; no timezone found

No data found for LATN. Skipping...

$MRC: possibly delisted; no timezone found

No data found for MRC. Skipping...

$CNCE: possibly delisted; no timezone found

No data found for CNCE. Skipping...

$PDLI: possibly delisted; no timezone found

No data found for PDLI. Skipping...

$ATRI: possibly delisted; no timezone found

No data found for ATRI. Skipping...

$MGU: possibly delisted; no timezone found
$CUBA: possibly delisted; no price data found  (1d 2020-04-02 -> 2026-02-01)

No data found for MGU. Skipping...
No data found for CUBA. Skipping...

$CHU: possibly delisted; no timezone found

No data found for CHU. Skipping...

$NICK: possibly delisted; no timezone found

No data found for NICK. Skipping...

$OPI: possibly delisted; no timezone found

No data found for OPI. Skipping...

$ASNA: possibly delisted; no timezone found
$JMP: possibly delisted; no timezone found

No data found for ASNA. Skipping...
No data found for JMP. Skipping...

$SCON: possibly delisted; no timezone found

No data found for SCON. Skipping...

$FARO: possibly delisted; no timezone found

No data found for FARO. Skipping...

$RYCE: possibly delisted; no timezone found

No data found for RYCE. Skipping...

$RESN: possibly delisted; no timezone found

No data found for RESN. Skipping...

$MBNKP: possibly delisted; no timezone found

No data found for MBNKP. Skipping...

$INFI: possibly delisted; no timezone found

No data found for INFI. Skipping...

$JMF: possibly delisted; no timezone found

No data found for JMF. Skipping...

$TGA: possibly delisted; no timezone found

No data found for TGA. Skipping...

$CBMB: possibly delisted; no timezone found

No data found for CBMB. Skipping...

$SCX: possibly delisted; no timezone found

No data found for SCX. Skipping...

$DNR: possibly delisted; no timezone found

No data found for DNR. Skipping...

$TSCBP: possibly delisted; no timezone found

No data found for TSCBP. Skipping...

$LACQ: possibly delisted; no timezone found
$TOTA: possibly delisted; no timezone found

No data found for LACQ. Skipping...
No data found for TOTA. Skipping...

$QTS: possibly delisted; no timezone found
$SOL: possibly delisted; no timezone found

No data found for QTS. Skipping...
No data found for SOL. Skipping...

$TA: possibly delisted; no timezone found

No data found for TA. Skipping...

$MLND: possibly delisted; no timezone found

No data found for MLND. Skipping...

$NEOS: possibly delisted; no timezone found

No data found for NEOS. Skipping...

$AGN: possibly delisted; no timezone found

No data found for AGN. Skipping...

$GRNV: possibly delisted; no timezone found
$JTD: possibly delisted; no timezone found

No data found for GRNV. Skipping...
No data found for JTD. Skipping...

$VRTU: possibly delisted; no timezone found

No data found for VRTU. Skipping...

$IBKC: possibly delisted; no timezone found
$VIAC: possibly delisted; no timezone found

No data found for IBKC. Skipping...
No data found for VIAC. Skipping...

$RBNC: possibly delisted; no timezone found

No data found for RBNC. Skipping...

$ETNB: possibly delisted; no timezone found

No data found for ETNB. Skipping...

$OSTK: possibly delisted; no timezone found

No data found for OSTK. Skipping...

$NBEV: possibly delisted; no timezone found

No data found for NBEV. Skipping...

$SOLN: possibly delisted; no timezone found

No data found for SOLN. Skipping...

$CYCCP: possibly delisted; no timezone found
$CPE: possibly delisted; no timezone found

No data found for CYCCP. Skipping...
No data found for CPE. Skipping...

$SOLY: possibly delisted; no timezone found

No data found for SOLY. Skipping...

$LMNL: possibly delisted; no timezone found

No data found for LMNL. Skipping...

$ONCS: possibly delisted; no timezone found

No data found for ONCS. Skipping...

$ELGX: possibly delisted; no timezone found

No data found for ELGX. Skipping...

$FDUSG: possibly delisted; no timezone found

No data found for FDUSG. Skipping...

$MTSL: possibly delisted; no timezone found

No data found for MTSL. Skipping...

$NAVB: possibly delisted; no timezone found

No data found for NAVB. Skipping...

$RARX: possibly delisted; no timezone found
$SNDE: possibly delisted; no timezone found

No data found for RARX. Skipping...
No data found for SNDE. Skipping...

$TANNI: possibly delisted; no timezone found

No data found for TANNI. Skipping...

$WUBA: possibly delisted; no timezone found

No data found for WUBA. Skipping...

$CFBI: possibly delisted; no timezone found

No data found for CFBI. Skipping...

$AGFS: possibly delisted; no timezone found

No data found for AGFS. Skipping...

$CMRX: possibly delisted; no timezone found

No data found for CMRX. Skipping...

$NAV: possibly delisted; no timezone found

No data found for NAV. Skipping...

$OPINI: possibly delisted; no timezone found
$PIY: possibly delisted; no timezone found

No data found for OPINI. Skipping...
No data found for PIY. Skipping...

$ICCH: possibly delisted; no timezone found
$BPMC: possibly delisted; no timezone found

No data found for ICCH. Skipping...
No data found for BPMC. Skipping...

$PRSP: possibly delisted; no timezone found

No data found for PRSP. Skipping...

$KRTX: possibly delisted; no timezone found

No data found for KRTX. Skipping...

$TELL: possibly delisted; no timezone found

No data found for TELL. Skipping...

$YVR: possibly delisted; no timezone found
$AKER: possibly delisted; no timezone found

No data found for YVR. Skipping...
No data found for AKER. Skipping...

$QTNT: possibly delisted; no timezone found

No data found for QTNT. Skipping...

$NGHCP: possibly delisted; no timezone found
$KIN: possibly delisted; no timezone found

No data found for NGHCP. Skipping...
No data found for KIN. Skipping...

$ARGO: possibly delisted; no timezone found

No data found for ARGO. Skipping...

$HCCHU: possibly delisted; no timezone found

No data found for HCCHU. Skipping...

$NVCN: possibly delisted; no timezone found

No data found for NVCN. Skipping...

$OBCI: possibly delisted; no timezone found

No data found for OBCI. Skipping...

$TIVO: possibly delisted; no timezone found

No data found for TIVO. Skipping...

In [3]:
!ls parquet_test_data/*.parquet | wc -l
!ls parquet_train_data/*.parquet | wc -l

    3940
    3940

It is interesting that almost 1900 companies or tickers are no longer available.

In [18]:
!ls yfinance_stock_data/*.csv | wc -l

    5884

## Parquet file
The following code is to compare the columns of the train (before 2020) and test (after 2020) datasets.

In [ ]:
cisco_train = pd.read_parquet("parquet_train_data/CSCO.parquet", engine='pyarrow', dtype_backend='pyarrow')
cisco_test = pd.read_parquet("parquet_test_data/CSCO.parquet", engine='pyarrow', dtype_backend='pyarrow')

In [ ]:
display(cisco_train.tail())
display(cisco_test.tail())

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-03-26 00:00:00,37.970001,40.919998,37.369999,40.580002,40.580002,38473300
2020-03-27 00:00:00,39.209999,40.150002,38.41,38.82,38.82,31278600
2020-03-30 00:00:00,39.450001,40.490002,38.959999,40.32,40.32,27120300
2020-03-31 00:00:00,40.130001,40.419998,39.110001,39.310001,39.310001,26014200
2020-04-01 00:00:00,38.169998,38.860001,37.869999,38.330002,38.330002,26773900

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2026-01-26 00:00:00,76.470001,77.419998,75.639999,77.010002,77.010002,24714400
2026-01-27 00:00:00,77.190002,78.910004,77.050003,78.68,78.68,17756700
2026-01-28 00:00:00,78.93,79.040001,78.019997,78.959999,78.959999,14022900
2026-01-29 00:00:00,79.110001,79.480003,77.629997,78.43,78.43,22642900
2026-01-30 00:00:00,78.089996,78.800003,77.720001,78.32,78.32,26458400

#### Exploratory Data Analysis (EDA)
##### Descriptive statistics
Book to refer Machine Learning and Data Science Blueprints for Finance, Hariom Tatsat et al [link](https://learning.oreilly.com/library/view/machine-learning-and/9781492073048/ch02.html#idm45864694385896)

## Stock indicator
Here I will experiment to test stock indicator python libraries to transform my dataset to useful indicator values. 
More importantly, I need my data in normalized values as it will be used for training Reinforcement learning model.