# Data Collection practice

<div class="alert alert-info"> In this notebook, I practiced to download data from Yahoo Finance using yfinance library. </div> 

---
#### Credits
I used yfinance library to download the market data from Yahoo! Finance API. 
<blockquote>
Yahoo!, Y!Finance, and Yahoo! finance are registered trademarks of Yahoo, Inc.
</blockquote>

#### yfinance experiment

In [1]:
import yfinance as yf
import pandas as pd
from pathlib import Path
import ta
import tqdm
from itertools import accumulate
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


sns.set_style("darkgrid")

In [2]:
ticker = "AAPL"
df = yf.download(tickers = ticker ,       # list of tickers
                  start = "2020-04-01", # start date
                  end = "2026-02-01",   # end date
                  interval = "1d",       # trading interval
                  ignore_tz = True,      # ignore timezone when aligning data from different exchanges?
                  prepost = False)

[*********************100%***********************]  1 of 1 completed

In [3]:
df.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-04-01  58.210094  60.097192  57.780001  59.560782  176218400
2020-04-02  59.181431  59.234589  57.241175  58.072369  165934000
2020-04-03  58.330910  59.367483  57.741342  58.666770  129880000
2020-04-06  63.419552  63.574189  60.256670  60.623938  201820400
2020-04-07  62.685009  65.649764  62.581112  65.432294  202887200

In [4]:
df.columns = df.columns.droplevel(1)
df.head()

Price           Close       High        Low       Open     Volume
Date
2020-04-01  58.210094  60.097192  57.780001  59.560782  176218400
2020-04-02  59.181431  59.234589  57.241175  58.072369  165934000
2020-04-03  58.330910  59.367483  57.741342  58.666770  129880000
2020-04-06  63.419552  63.574189  60.256670  60.623938  201820400
2020-04-07  62.685009  65.649764  62.581112  65.432294  202887200

In [23]:
apple_stock = yf.Ticker(ticker)
apple_history=apple_stock.history(start = "2020-04-02", # start date
                  end = "2026-02-01",   # end date
                  interval = "1d",       # trading interval
                  prepost = False,
                  auto_adjust = False
)
apple_history.tail()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2026-01-26 00:00:00-05:00,251.479996,256.559998,249.800003,255.410004,255.171234,55969200,0.0,0.0
2026-01-27 00:00:00-05:00,259.170013,261.950012,258.209991,258.269989,258.028534,49648300,0.0,0.0
2026-01-28 00:00:00-05:00,257.649994,258.859985,254.509995,256.440002,256.200287,41288000,0.0,0.0
2026-01-29 00:00:00-05:00,258.000000,259.649994,254.410004,258.279999,258.038544,67253000,0.0,0.0
2026-01-30 00:00:00-05:00,255.169998,261.899994,252.179993,259.480011,259.237427,92443400,0.0,0.0

In [24]:
if apple_history.index.tz is not None:
    apple_history.index = apple_history.index.tz_localize(None)

In [20]:
apple_history.tail()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2026-01-26,251.479996,256.559998,249.800003,255.410004,255.171234,55969200,0.0,0.0
2026-01-27,259.170013,261.950012,258.209991,258.269989,258.028534,49648300,0.0,0.0
2026-01-28,257.649994,258.859985,254.509995,256.440002,256.200287,41288000,0.0,0.0
2026-01-29,258.000000,259.649994,254.410004,258.279999,258.038544,67253000,0.0,0.0
2026-01-30,255.169998,261.899994,252.179993,259.480011,259.237427,92443400,0.0,0.0

In [22]:
apple_history[['Open', 'High', 'Low', 'Close', 'Adj Close','Volume']].head()

                 Open       High        Low      Close  Adj Close     Volume
Date
2020-04-02  60.084999  61.287498  59.224998  61.232498  59.181427  165934000
2020-04-03  60.700001  61.424999  59.742500  60.352501  58.330910  129880000
2020-04-06  62.724998  65.777496  62.345001  65.617500  63.419556  201820400
2020-04-07  67.699997  67.925003  64.750000  64.857498  62.685017  202887200
2020-04-08  65.684998  66.842499  65.307503  66.517502  64.289413  168895200

## Conclusion 

🍋 Tested to download the historical stock price data using yfinance. 

|Date (YYYY-MM-DD)|Version|Created By|  
|--|--|--|
|2026-02-26|1.0|Battogtokh Baasanjav|